// A1 German vocabulary (252 words) extracted from the StudyGerman.io A1 list.
// type: noun | adj | adv   art: der/die/das   pl: plural (nouns only, when commonly used)
window.VOCAB = [{"id": 1,"de": "der Mann","en": "man","ex": "Der Mann liest ein Buch.","exEn": "The man is reading a book.","type": "noun","cat": "Home, people & food","art": "der","noun": "Mann","pl": "Männer"},
{"id": 2,"de": "die Frau","en": "woman","ex": "Die Frau geht zur Arbeit.","exEn": "The woman goes to work.","type": "noun","cat": "Home, people & food","art": "die","noun": "Frau","pl": "Frauen"},
{"id": 3,"de": "das Kind","en": "child","ex": "Das Kind spielt im Garten.","exEn": "The child plays in the garden.","type": "noun","cat": "Home, people & food","art": "das","noun": "Kind","pl": "Kinder"},
{"id": 4,"de": "der Tisch","en": "table","ex": "Der Tisch ist groß.","exEn": "The table is big.","type": "noun","cat": "Home, people & food","art": "der","noun": "Tisch","pl": "Tische"},
{"id": 5,"de": "der Stuhl","en": "chair","ex": "Der Stuhl steht am Tisch.","exEn": "The chair stands at the table.","type": "noun","cat": "Home, people & food","art": "der","noun": "Stuhl","pl": "Stühle"},
{"id": 6,"de": "das Buch","en": "book","ex": "Ich lese ein Buch.","exEn": "I am reading a book.","type": "noun","cat": "Home, people & food","art": "das","noun": "Buch","pl": "Bücher"},
{"id": 7,"de": "die Tür","en": "door","ex": "Die Tür ist offen.","exEn": "The door is open.","type": "noun","cat": "Home, people & food","art": "die","noun": "Tür","pl": "Türen"},
{"id": 8,"de": "das Fenster","en": "window","ex": "Das Fenster ist geschlossen.","exEn": "The window is closed.","type": "noun","cat": "Home, people & food","art": "das","noun": "Fenster","pl": "Fenster"},
{"id": 9,"de": "das Haus","en": "house","ex": "Wir wohnen in einem Haus.","exEn": "We live in a house.","type": "noun","cat": "Home, people & food","art": "das","noun": "Haus","pl": "Häuser"},
{"id": 10,"de": "die Wohnung","en": "apartment","ex": "Die Wohnung ist schön.","exEn": "The apartment is nice.","type": "noun","cat": "Home, people & food","art": "die","noun": "Wohnung","pl": "Wohnungen"},
{"id": 11,"de": "das Auto","en": "car","ex": "Das Auto ist rot.","exEn": "The car is red.","type": "noun","cat": "Home, people & food","art": "das","noun": "Auto","pl": "Autos"},
{"id": 12,"de": "der Hund","en": "dog","ex": "Der Hund bellt.","exEn": "The dog barks.","type": "noun","cat": "Home, people & food","art": "der","noun": "Hund","pl": "Hunde"},
{"id": 13,"de": "die Katze","en": "cat","ex": "Die Katze schläft.","exEn": "The cat sleeps.","type": "noun","cat": "Home, people & food","art": "die","noun": "Katze","pl": "Katzen"},
{"id": 14,"de": "das Wasser","en": "water","ex": "Ich trinke Wasser.","exEn": "I drink water.","type": "noun","cat": "Home, people & food","art": "das","noun": "Wasser"},
{"id": 15,"de": "das Brot","en": "bread","ex": "Ich esse Brot.","exEn": "I eat bread.","type": "noun","cat": "Home, people & food","art": "das","noun": "Brot","pl": "Brote"},
{"id": 16,"de": "die Milch","en": "milk","ex": "Die Milch ist kalt.","exEn": "The milk is cold.","type": "noun","cat": "Home, people & food","art": "die","noun": "Milch"},
{"id": 17,"de": "der Apfel","en": "apple","ex": "Der Apfel ist rot.","exEn": "The apple is red.","type": "noun","cat": "Home, people & food","art": "der","noun": "Apfel","pl": "Äpfel"},
{"id": 18,"de": "die Banane","en": "banana","ex": "Die Banane ist gelb.","exEn": "The banana is yellow.","type": "noun","cat": "Home, people & food","art": "die","noun": "Banane","pl": "Bananen"},
{"id": 19,"de": "der Tag","en": "day","ex": "Heute ist ein schöner Tag.","exEn": "Today is a beautiful day.","type": "noun","cat": "Time units","art": "der","noun": "Tag","pl": "Tage"},
{"id": 20,"de": "die Nacht","en": "night","ex": "In der Nacht schlafe ich.","exEn": "At night I sleep.","type": "noun","cat": "Time units","art": "die","noun": "Nacht","pl": "Nächte"},
{"id": 21,"de": "die Woche","en": "week","ex": "Die Woche hat sieben Tage.","exEn": "The week has seven days.","type": "noun","cat": "Time units","art": "die","noun": "Woche","pl": "Wochen"},
{"id": 22,"de": "der Monat","en": "month","ex": "Ein Monat hat 30 oder 31 Tage.","exEn": "A month has 30 or 31 days.","type": "noun","cat": "Time units","art": "der","noun": "Monat","pl": "Monate"},
{"id": 23,"de": "das Jahr","en": "year","ex": "Ein Jahr hat zwölf Monate.","exEn": "A year has twelve months.","type": "noun","cat": "Time units","art": "das","noun": "Jahr","pl": "Jahre"},
{"id": 24,"de": "die Uhr","en": "clock/watch","ex": "Die Uhr zeigt drei Uhr.","exEn": "The clock shows three o'clock.","type": "noun","cat": "Time units","art": "die","noun": "Uhr","pl": "Uhren"},
{"id": 25,"de": "die Zeit","en": "time","ex": "Ich habe keine Zeit.","exEn": "I have no time.","type": "noun","cat": "Time units","art": "die","noun": "Zeit","pl": "Zeiten"},
{"id": 26,"de": "der Freund","en": "friend (male)","ex": "Mein Freund ist nett.","exEn": "My friend is nice.","type": "noun","cat": "Family, school & work","art": "der","noun": "Freund","pl": "Freunde"},
{"id": 27,"de": "die Freundin","en": "friend (female)","ex": "Meine Freundin hilft mir.","exEn": "My friend helps me.","type": "noun","cat": "Family, school & work","art": "die","noun": "Freundin","pl": "Freundinnen"},
{"id": 28,"de": "die Familie","en": "family","ex": "Meine Familie ist groß.","exEn": "My family is big.","type": "noun","cat": "Family, school & work","art": "die","noun": "Familie","pl": "Familien"},
{"id": 29,"de": "die Mutter","en": "mother","ex": "Meine Mutter kocht gut.","exEn": "My mother cooks well.","type": "noun","cat": "Family, school & work","art": "die","noun": "Mutter","pl": "Mütter"},
{"id": 30,"de": "der Vater","en": "father","ex": "Mein Vater arbeitet viel.","exEn": "My father works a lot.","type": "noun","cat": "Family, school & work","art": "der","noun": "Vater","pl": "Väter"},
{"id": 31,"de": "der Bruder","en": "brother","ex": "Mein Bruder ist älter.","exEn": "My brother is older.","type": "noun","cat": "Family, school & work","art": "der","noun": "Bruder","pl": "Brüder"},
{"id": 32,"de": "die Schwester","en": "sister","ex": "Meine Schwester studiert.","exEn": "My sister studies.","type": "noun","cat": "Family, school & work","art": "die","noun": "Schwester","pl": "Schwestern"},
{"id": 33,"de": "die Schule","en": "school","ex": "Ich gehe zur Schule.","exEn": "I go to school.","type": "noun","cat": "Family, school & work","art": "die","noun": "Schule","pl": "Schulen"},
{"id": 34,"de": "der Lehrer","en": "teacher (male)","ex": "Der Lehrer erklärt gut.","exEn": "The teacher explains well.","type": "noun","cat": "Family, school & work","art": "der","noun": "Lehrer","pl": "Lehrer"},
{"id": 35,"de": "die Lehrerin","en": "teacher (female)","ex": "Die Lehrerin ist freundlich.","exEn": "The teacher is friendly.","type": "noun","cat": "Family, school & work","art": "die","noun": "Lehrerin","pl": "Lehrerinnen"},
{"id": 36,"de": "der Student","en": "student (male)","ex": "Der Student lernt Deutsch.","exEn": "The student learns German.","type": "noun","cat": "Family, school & work","art": "der","noun": "Student","pl": "Studenten"},
{"id": 37,"de": "die Studentin","en": "student (female)","ex": "Die Studentin liest viel.","exEn": "The student reads a lot.","type": "noun","cat": "Family, school & work","art": "die","noun": "Studentin","pl": "Studentinnen"},
{"id": 38,"de": "die Arbeit","en": "work","ex": "Ich gehe zur Arbeit.","exEn": "I go to work.","type": "noun","cat": "Family, school & work","art": "die","noun": "Arbeit","pl": "Arbeiten"},
{"id": 39,"de": "der Beruf","en": "profession","ex": "Was ist dein Beruf?","exEn": "What is your profession?","type": "noun","cat": "Family, school & work","art": "der","noun": "Beruf","pl": "Berufe"},
{"id": 40,"de": "das Geld","en": "money","ex": "Ich habe kein Geld.","exEn": "I have no money.","type": "noun","cat": "Family, school & work","art": "das","noun": "Geld","pl": "Gelder"},
{"id": 41,"de": "die Stadt","en": "city","ex": "Die Stadt ist groß.","exEn": "The city is big.","type": "noun","cat": "Town & places","art": "die","noun": "Stadt","pl": "Städte"},
{"id": 42,"de": "das Land","en": "country","ex": "Deutschland ist ein Land.","exEn": "Germany is a country.","type": "noun","cat": "Town & places","art": "das","noun": "Land","pl": "Länder"},
{"id": 43,"de": "die Straße","en": "street","ex": "Die Straße ist lang.","exEn": "The street is long.","type": "noun","cat": "Town & places","art": "die","noun": "Straße","pl": "Straßen"},
{"id": 44,"de": "der Park","en": "park","ex": "Wir gehen in den Park.","exEn": "We go to the park.","type": "noun","cat": "Town & places","art": "der","noun": "Park","pl": "Parks"},
{"id": 45,"de": "das Restaurant","en": "restaurant","ex": "Wir essen im Restaurant.","exEn": "We eat in the restaurant.","type": "noun","cat": "Town & places","art": "das","noun": "Restaurant","pl": "Restaurants"},
{"id": 46,"de": "das Café","en": "café","ex": "Ich trinke Kaffee im Café.","exEn": "I drink coffee in the café.","type": "noun","cat": "Town & places","art": "das","noun": "Café","pl": "Cafés"},
{"id": 47,"de": "der Supermarkt","en": "supermarket","ex": "Ich kaufe im Supermarkt ein.","exEn": "I shop at the supermarket.","type": "noun","cat": "Town & places","art": "der","noun": "Supermarkt","pl": "Supermärkte"},
{"id": 48,"de": "das Geschäft","en": "shop","ex": "Das Geschäft ist geschlossen.","exEn": "The shop is closed.","type": "noun","cat": "Town & places","art": "das","noun": "Geschäft","pl": "Geschäfte"},
{"id": 49,"de": "die Bank","en": "bank","ex": "Ich gehe zur Bank.","exEn": "I go to the bank.","type": "noun","cat": "Town & places","art": "die","noun": "Bank","pl": "Banken"},
{"id": 50,"de": "das Krankenhaus","en": "hospital","ex": "Er ist im Krankenhaus.","exEn": "He is in the hospital.","type": "noun","cat": "Town & places","art": "das","noun": "Krankenhaus","pl": "Krankenhäuser"},
{"id": 51,"de": "die Polizei","en": "police","ex": "Rufe die Polizei!","exEn": "Call the police!","type": "noun","cat": "Town & places","art": "die","noun": "Polizei"},
{"id": 52,"de": "das Telefon","en": "telephone","ex": "Das Telefon klingelt.","exEn": "The telephone rings.","type": "noun","cat": "Town & places","art": "das","noun": "Telefon","pl": "Telefone"},
{"id": 53,"de": "der Computer","en": "computer","ex": "Ich arbeite am Computer.","exEn": "I work on the computer.","type": "noun","cat": "Town & places","art": "der","noun": "Computer","pl": "Computer"},
{"id": 54,"de": "das Internet","en": "internet","ex": "Ich surfe im Internet.","exEn": "I surf the internet.","type": "noun","cat": "Town & places","art": "das","noun": "Internet"},
{"id": 55,"de": "die E-Mail","en": "email","ex": "Ich schreibe eine E-Mail.","exEn": "I write an email.","type": "noun","cat": "Town & places","art": "die","noun": "E-Mail","pl": "E-Mails"},
{"id": 56,"de": "der Brief","en": "letter","ex": "Ich schreibe einen Brief.","exEn": "I write a letter.","type": "noun","cat": "Town & places","art": "der","noun": "Brief","pl": "Briefe"},
{"id": 57,"de": "die Post","en": "post office","ex": "Ich gehe zur Post.","exEn": "I go to the post office.","type": "noun","cat": "Town & places","art": "die","noun": "Post"},
{"id": 58,"de": "der Bahnhof","en": "train station","ex": "Wir treffen uns am Bahnhof.","exEn": "We meet at the train station.","type": "noun","cat": "Town & places","art": "der","noun": "Bahnhof","pl": "Bahnhöfe"},
{"id": 59,"de": "der Flughafen","en": "airport","ex": "Der Flughafen ist weit weg.","exEn": "The airport is far away.","type": "noun","cat": "Town & places","art": "der","noun": "Flughafen","pl": "Flughäfen"},
{"id": 60,"de": "das Hotel","en": "hotel","ex": "Wir übernachten im Hotel.","exEn": "We stay at the hotel.","type": "noun","cat": "Town & places","art": "das","noun": "Hotel","pl": "Hotels"},
{"id": 61,"de": "der Strand","en": "beach","ex": "Wir gehen zum Strand.","exEn": "We go to the beach.","type": "noun","cat": "Nature & weather","art": "der","noun": "Strand","pl": "Strände"},
{"id": 62,"de": "das Meer","en": "sea","ex": "Das Meer ist blau.","exEn": "The sea is blue.","type": "noun","cat": "Nature & weather","art": "das","noun": "Meer","pl": "Meere"},
{"id": 63,"de": "der Berg","en": "mountain","ex": "Der Berg ist hoch.","exEn": "The mountain is high.","type": "noun","cat": "Nature & weather","art": "der","noun": "Berg","pl": "Berge"},
{"id": 64,"de": "der Wald","en": "forest","ex": "Wir spazieren im Wald.","exEn": "We walk in the forest.","type": "noun","cat": "Nature & weather","art": "der","noun": "Wald","pl": "Wälder"},
{"id": 65,"de": "der Fluss","en": "river","ex": "Der Fluss ist lang.","exEn": "The river is long.","type": "noun","cat": "Nature & weather","art": "der","noun": "Fluss","pl": "Flüsse"},
{"id": 66,"de": "der See","en": "lake","ex": "Der See ist schön.","exEn": "The lake is beautiful.","type": "noun","cat": "Nature & weather","art": "der","noun": "See","pl": "Seen"},
{"id": 67,"de": "die Sonne","en": "sun","ex": "Die Sonne scheint.","exEn": "The sun shines.","type": "noun","cat": "Nature & weather","art": "die","noun": "Sonne","pl": "Sonnen"},
{"id": 68,"de": "der Mond","en": "moon","ex": "Der Mond ist hell.","exEn": "The moon is bright.","type": "noun","cat": "Nature & weather","art": "der","noun": "Mond","pl": "Monde"},
{"id": 69,"de": "der Stern","en": "star","ex": "Die Sterne leuchten.","exEn": "The stars shine.","type": "noun","cat": "Nature & weather","art": "der","noun": "Stern","pl": "Sterne"},
{"id": 70,"de": "der Himmel","en": "sky","ex": "Der Himmel ist blau.","exEn": "The sky is blue.","type": "noun","cat": "Nature & weather","art": "der","noun": "Himmel","pl": "Himmel"},
{"id": 71,"de": "die Wolke","en": "cloud","ex": "Die Wolke ist weiß.","exEn": "The cloud is white.","type": "noun","cat": "Nature & weather","art": "die","noun": "Wolke","pl": "Wolken"},
{"id": 72,"de": "der Regen","en": "rain","ex": "Der Regen ist stark.","exEn": "The rain is heavy.","type": "noun","cat": "Nature & weather","art": "der","noun": "Regen"},
{"id": 73,"de": "der Schnee","en": "snow","ex": "Ich mag Schnee.","exEn": "I like snow.","type": "noun","cat": "Nature & weather","art": "der","noun": "Schnee"},
{"id": 74,"de": "der Wind","en": "wind","ex": "Der Wind weht.","exEn": "The wind blows.","type": "noun","cat": "Nature & weather","art": "der","noun": "Wind","pl": "Winde"},
{"id": 75,"de": "die Temperatur","en": "temperature","ex": "Die Temperatur ist hoch.","exEn": "The temperature is high.","type": "noun","cat": "Nature & weather","art": "die","noun": "Temperatur","pl": "Temperaturen"},
{"id": 76,"de": "das Wetter","en": "weather","ex": "Das Wetter ist schön.","exEn": "The weather is nice.","type": "noun","cat": "Nature & weather","art": "das","noun": "Wetter"},
{"id": 77,"de": "die Farbe","en": "color","ex": "Meine Lieblingsfarbe ist blau.","exEn": "My favorite color is blue.","type": "noun","cat": "Colours","art": "die","noun": "Farbe","pl": "Farben"},
{"id": 78,"de": "rot","en": "red","ex": "Die Rose ist rot.","exEn": "The rose is red.","type": "adj","cat": "Colours"},
{"id": 79,"de": "blau","en": "blue","ex": "Der Himmel ist blau.","exEn": "The sky is blue.","type": "adj","cat": "Colours"},
{"id": 80,"de": "grün","en": "green","ex": "Das Gras ist grün.","exEn": "The grass is green.","type": "adj","cat": "Colours"},
{"id": 81,"de": "gelb","en": "yellow","ex": "Die Sonne ist gelb.","exEn": "The sun is yellow.","type": "adj","cat": "Colours"},
{"id": 82,"de": "schwarz","en": "black","ex": "Die Nacht ist schwarz.","exEn": "The night is black.","type": "adj","cat": "Colours"},
{"id": 83,"de": "weiß","en": "white","ex": "Der Schnee ist weiß.","exEn": "The snow is white.","type": "adj","cat": "Colours"},
{"id": 84,"de": "groß","en": "big/large","ex": "Das Haus ist groß.","exEn": "The house is big.","type": "adj","cat": "Describing things"},
{"id": 85,"de": "klein","en": "small","ex": "Das Kind ist klein.","exEn": "The child is small.","type": "adj","cat": "Describing things"},
{"id": 86,"de": "lang","en": "long","ex": "Die Straße ist lang.","exEn": "The street is long.","type": "adj","cat": "Describing things"},
{"id": 87,"de": "kurz","en": "short","ex": "Das Haar ist kurz.","exEn": "The hair is short.","type": "adj","cat": "Describing things"},
{"id": 88,"de": "hoch","en": "high/tall","ex": "Der Berg ist hoch.","exEn": "The mountain is high.","type": "adj","cat": "Describing things"},
{"id": 89,"de": "niedrig","en": "low","ex": "Der Tisch ist niedrig.","exEn": "The table is low.","type": "adj","cat": "Describing things"},
{"id": 90,"de": "breit","en": "wide","ex": "Die Straße ist breit.","exEn": "The street is wide.","type": "adj","cat": "Describing things"},
{"id": 91,"de": "schmal","en": "narrow","ex": "Der Weg ist schmal.","exEn": "The path is narrow.","type": "adj","cat": "Describing things"},
{"id": 92,"de": "schwer","en": "heavy/difficult","ex": "Die Kiste ist schwer.","exEn": "The box is heavy.","type": "adj","cat": "Describing things"},
{"id": 93,"de": "leicht","en": "light/easy","ex": "Die Tasche ist leicht.","exEn": "The bag is light.","type": "adj","cat": "Describing things"},
{"id": 94,"de": "alt","en": "old","ex": "Das Haus ist alt.","exEn": "The house is old.","type": "adj","cat": "Describing things"},
{"id": 95,"de": "neu","en": "new","ex": "Das Auto ist neu.","exEn": "The car is new.","type": "adj","cat": "Describing things"},
{"id": 96,"de": "jung","en": "young","ex": "Das Kind ist jung.","exEn": "The child is young.","type": "adj","cat": "Describing things"},
{"id": 97,"de": "gut","en": "good","ex": "Das Essen ist gut.","exEn": "The food is good.","type": "adj","cat": "Describing things"},
{"id": 98,"de": "schlecht","en": "bad","ex": "Das Wetter ist schlecht.","exEn": "The weather is bad.","type": "adj","cat": "Describing things"},
{"id": 99,"de": "schön","en": "beautiful","ex": "Die Blume ist schön.","exEn": "The flower is beautiful.","type": "adj","cat": "Describing things"},
{"id": 100,"de": "hässlich","en": "ugly","ex": "Das Bild ist hässlich.","exEn": "The picture is ugly.","type": "adj","cat": "Describing things"},
{"id": 101,"de": "sauber","en": "clean","ex": "Das Zimmer ist sauber.","exEn": "The room is clean.","type": "adj","cat": "Describing things"},
{"id": 102,"de": "schmutzig","en": "dirty","ex": "Die Kleidung ist schmutzig.","exEn": "The clothes are dirty.","type": "adj","cat": "Describing things"},
{"id": 103,"de": "warm","en": "warm","ex": "Das Wasser ist warm.","exEn": "The water is warm.","type": "adj","cat": "Describing things"},
{"id": 104,"de": "kalt","en": "cold","ex": "Das Eis ist kalt.","exEn": "The ice is cold.","type": "adj","cat": "Describing things"},
{"id": 105,"de": "heiß","en": "hot","ex": "Der Kaffee ist heiß.","exEn": "The coffee is hot.","type": "adj","cat": "Describing things"},
{"id": 106,"de": "kühl","en": "cool","ex": "Die Luft ist kühl.","exEn": "The air is cool.","type": "adj","cat": "Describing things"},
{"id": 107,"de": "schnell","en": "fast","ex": "Das Auto ist schnell.","exEn": "The car is fast.","type": "adj","cat": "Describing things"},
{"id": 108,"de": "langsam","en": "slow","ex": "Die Schildkröte ist langsam.","exEn": "The turtle is slow.","type": "adj","cat": "Describing things"},
{"id": 109,"de": "teuer","en": "expensive","ex": "Das Auto ist teuer.","exEn": "The car is expensive.","type": "adj","cat": "Describing things"},
{"id": 110,"de": "billig","en": "cheap","ex": "Das Buch ist billig.","exEn": "The book is cheap.","type": "adj","cat": "Describing things"},
{"id": 111,"de": "frei","en": "free","ex": "Der Platz ist frei.","exEn": "The seat is free.","type": "adj","cat": "Describing things"},
{"id": 112,"de": "voll","en": "full","ex": "Das Glas ist voll.","exEn": "The glass is full.","type": "adj","cat": "Describing things"},
{"id": 113,"de": "leer","en": "empty","ex": "Die Flasche ist leer.","exEn": "The bottle is empty.","type": "adj","cat": "Describing things"},
{"id": 114,"de": "richtig","en": "correct/right","ex": "Die Antwort ist richtig.","exEn": "The answer is correct.","type": "adj","cat": "Describing things"},
{"id": 115,"de": "falsch","en": "wrong/false","ex": "Das ist falsch.","exEn": "That is wrong.","type": "adj","cat": "Describing things"},
{"id": 116,"de": "wahr","en": "true","ex": "Das ist wahr.","exEn": "That is true.","type": "adj","cat": "Describing things"},
{"id": 117,"de": "wichtig","en": "important","ex": "Das ist wichtig.","exEn": "That is important.","type": "adj","cat": "Describing things"},
{"id": 118,"de": "unwichtig","en": "unimportant","ex": "Das ist unwichtig.","exEn": "That is unimportant.","type": "adj","cat": "Describing things"},
{"id": 119,"de": "interessant","en": "interesting","ex": "Das Buch ist interessant.","exEn": "The book is interesting.","type": "adj","cat": "Describing things"},
{"id": 120,"de": "langweilig","en": "boring","ex": "Der Film ist langweilig.","exEn": "The movie is boring.","type": "adj","cat": "Describing things"},
{"id": 121,"de": "einfach","en": "simple/easy","ex": "Die Aufgabe ist einfach.","exEn": "The task is simple.","type": "adj","cat": "Describing things"},
{"id": 122,"de": "schwierig","en": "difficult","ex": "Die Prüfung ist schwierig.","exEn": "The exam is difficult.","type": "adj","cat": "Describing things"},
{"id": 123,"de": "möglich","en": "possible","ex": "Das ist möglich.","exEn": "That is possible.","type": "adj","cat": "Describing things"},
{"id": 124,"de": "unmöglich","en": "impossible","ex": "Das ist unmöglich.","exEn": "That is impossible.","type": "adj","cat": "Describing things"},
{"id": 125,"de": "nötig","en": "necessary","ex": "Das ist nötig.","exEn": "That is necessary.","type": "adj","cat": "Describing things"},
{"id": 126,"de": "unnötig","en": "unnecessary","ex": "Das ist unnötig.","exEn": "That is unnecessary.","type": "adj","cat": "Describing things"},
{"id": 127,"de": "nützlich","en": "useful","ex": "Das ist nützlich.","exEn": "That is useful.","type": "adj","cat": "Describing things"},
{"id": 128,"de": "nutzlos","en": "useless","ex": "Das ist nutzlos.","exEn": "That is useless.","type": "adj","cat": "Describing things"},
{"id": 129,"de": "fertig","en": "ready/finished","ex": "Ich bin fertig.","exEn": "I am finished.","type": "adj","cat": "Feelings & states"},
{"id": 130,"de": "bereit","en": "ready","ex": "Ich bin bereit.","exEn": "I am ready.","type": "adj","cat": "Feelings & states"},
{"id": 131,"de": "müde","en": "tired","ex": "Ich bin müde.","exEn": "I am tired.","type": "adj","cat": "Feelings & states"},
{"id": 132,"de": "wach","en": "awake","ex": "Ich bin wach.","exEn": "I am awake.","type": "adj","cat": "Feelings & states"},
{"id": 133,"de": "gesund","en": "healthy","ex": "Ich bin gesund.","exEn": "I am healthy.","type": "adj","cat": "Feelings & states"},
{"id": 134,"de": "krank","en": "sick","ex": "Ich bin krank.","exEn": "I am sick.","type": "adj","cat": "Feelings & states"},
{"id": 135,"de": "stark","en": "strong","ex": "Er ist stark.","exEn": "He is strong.","type": "adj","cat": "Feelings & states"},
{"id": 136,"de": "schwach","en": "weak","ex": "Sie ist schwach.","exEn": "She is weak.","type": "adj","cat": "Feelings & states"},
{"id": 137,"de": "reich","en": "rich","ex": "Er ist reich.","exEn": "He is rich.","type": "adj","cat": "Feelings & states"},
{"id": 138,"de": "arm","en": "poor","ex": "Sie ist arm.","exEn": "She is poor.","type": "adj","cat": "Feelings & states"},
{"id": 139,"de": "glücklich","en": "happy","ex": "Ich bin glücklich.","exEn": "I am happy.","type": "adj","cat": "Feelings & states"},
{"id": 140,"de": "traurig","en": "sad","ex": "Ich bin traurig.","exEn": "I am sad.","type": "adj","cat": "Feelings & states"},
{"id": 141,"de": "zufrieden","en": "satisfied","ex": "Ich bin zufrieden.","exEn": "I am satisfied.","type": "adj","cat": "Feelings & states"},
{"id": 142,"de": "unzufrieden","en": "dissatisfied","ex": "Ich bin unzufrieden.","exEn": "I am dissatisfied.","type": "adj","cat": "Feelings & states"},
{"id": 143,"de": "ruhig","en": "quiet/calm","ex": "Das Kind ist ruhig.","exEn": "The child is quiet.","type": "adj","cat": "Feelings & states"},
{"id": 144,"de": "laut","en": "loud","ex": "Die Musik ist laut.","exEn": "The music is loud.","type": "adj","cat": "Feelings & states"},
{"id": 145,"de": "still","en": "silent","ex": "Die Bibliothek ist still.","exEn": "The library is silent.","type": "adj","cat": "Feelings & states"},
{"id": 146,"de": "leise","en": "quiet","ex": "Sprich leise!","exEn": "Speak quietly!","type": "adj","cat": "Feelings & states"},
{"id": 147,"de": "hell","en": "bright/light","ex": "Das Zimmer ist hell.","exEn": "The room is bright.","type": "adj","cat": "Feelings & states"},
{"id": 148,"de": "dunkel","en": "dark","ex": "Die Nacht ist dunkel.","exEn": "The night is dark.","type": "adj","cat": "Feelings & states"},
{"id": 149,"de": "klar","en": "clear","ex": "Das Wasser ist klar.","exEn": "The water is clear.","type": "adj","cat": "Feelings & states"},
{"id": 150,"de": "bewölkt","en": "cloudy","ex": "Der Himmel ist bewölkt.","exEn": "The sky is cloudy.","type": "adj","cat": "Feelings & states"},
{"id": 151,"de": "trocken","en": "dry","ex": "Die Kleidung ist trocken.","exEn": "The clothes are dry.","type": "adj","cat": "Feelings & states"},
{"id": 152,"de": "nass","en": "wet","ex": "Die Kleidung ist nass.","exEn": "The clothes are wet.","type": "adj","cat": "Feelings & states"},
{"id": 153,"de": "weich","en": "soft","ex": "Das Bett ist weich.","exEn": "The bed is soft.","type": "adj","cat": "Feelings & states"},
{"id": 154,"de": "hart","en": "hard","ex": "Der Stein ist hart.","exEn": "The stone is hard.","type": "adj","cat": "Feelings & states"},
{"id": 155,"de": "süß","en": "sweet","ex": "Der Kuchen ist süß.","exEn": "The cake is sweet.","type": "adj","cat": "Feelings & states"},
{"id": 156,"de": "sauer","en": "sour","ex": "Die Zitrone ist sauer.","exEn": "The lemon is sour.","type": "adj","cat": "Feelings & states"},
{"id": 157,"de": "salzig","en": "salty","ex": "Das Essen ist salzig.","exEn": "The food is salty.","type": "adj","cat": "Feelings & states"},
{"id": 158,"de": "bitter","en": "bitter","ex": "Der Kaffee ist bitter.","exEn": "The coffee is bitter.","type": "adj","cat": "Feelings & states"},
{"id": 159,"de": "scharf","en": "spicy/sharp","ex": "Das Essen ist scharf.","exEn": "The food is spicy.","type": "adj","cat": "Feelings & states"},
{"id": 160,"de": "mild","en": "mild","ex": "Das Essen ist mild.","exEn": "The food is mild.","type": "adj","cat": "Feelings & states"},
{"id": 161,"de": "frisch","en": "fresh","ex": "Das Brot ist frisch.","exEn": "The bread is fresh.","type": "adj","cat": "Feelings & states"},
{"id": 162,"de": "lecker","en": "delicious","ex": "Das Essen ist lecker.","exEn": "The food is delicious.","type": "adj","cat": "Feelings & states"},
{"id": 163,"de": "ekelhaft","en": "disgusting","ex": "Das Essen ist ekelhaft.","exEn": "The food is disgusting.","type": "adj","cat": "Feelings & states"},
{"id": 164,"de": "hungrig","en": "hungry","ex": "Ich bin hungrig.","exEn": "I am hungry.","type": "adj","cat": "Feelings & states"},
{"id": 165,"de": "satt","en": "full (after eating)","ex": "Ich bin satt.","exEn": "I am full.","type": "adj","cat": "Feelings & states"},
{"id": 166,"de": "durstig","en": "thirsty","ex": "Ich bin durstig.","exEn": "I am thirsty.","type": "adj","cat": "Feelings & states"},
{"id": 167,"de": "ordentlich","en": "tidy","ex": "Das Zimmer ist ordentlich.","exEn": "The room is tidy.","type": "adj","cat": "Feelings & states"},
{"id": 168,"de": "unordentlich","en": "messy","ex": "Das Zimmer ist unordentlich.","exEn": "The room is messy.","type": "adj","cat": "Feelings & states"},
{"id": 169,"de": "pünktlich","en": "punctual","ex": "Ich bin pünktlich.","exEn": "I am punctual.","type": "adj","cat": "Feelings & states"},
{"id": 170,"de": "spät","en": "late","ex": "Ich bin spät.","exEn": "I am late.","type": "adj","cat": "Feelings & states"},
{"id": 171,"de": "früh","en": "early","ex": "Ich bin früh.","exEn": "I am early.","type": "adj","cat": "Feelings & states"},
{"id": 172,"de": "sofort","en": "immediately","ex": "Komm sofort!","exEn": "Come immediately!","type": "adv","cat": "Feelings & states"},
{"id": 173,"de": "später","en": "later","ex": "Wir sehen uns später.","exEn": "We'll see each other later.","type": "adv","cat": "Feelings & states"},
{"id": 174,"de": "jetzt","en": "now","ex": "Ich gehe jetzt.","exEn": "I am going now.","type": "adv","cat": "Feelings & states"},
{"id": 175,"de": "heute","en": "today","ex": "Heute ist Montag.","exEn": "Today is Monday.","type": "adv","cat": "Days & relative time"},
{"id": 176,"de": "gestern","en": "yesterday","ex": "Gestern war Sonntag.","exEn": "Yesterday was Sunday.","type": "adv","cat": "Days & relative time"},
{"id": 177,"de": "morgen","en": "tomorrow","ex": "Morgen ist Dienstag.","exEn": "Tomorrow is Tuesday.","type": "adv","cat": "Days & relative time"},
{"id": 178,"de": "vorgestern","en": "the day before yesterday","ex": "Vorgestern war Samstag.","exEn": "The day before yesterday was Saturday.","type": "adv","cat": "Days & relative time"},
{"id": 179,"de": "übermorgen","en": "the day after tomorrow","ex": "Übermorgen ist Mittwoch.","exEn": "The day after tomorrow is Wednesday.","type": "adv","cat": "Days & relative time"},
{"id": 180,"de": "heute Morgen","en": "this morning","ex": "Heute Morgen war ich müde.","exEn": "This morning I was tired.","type": "adv","cat": "Days & relative time"},
{"id": 181,"de": "heute Abend","en": "this evening","ex": "Heute Abend gehe ich ins Kino.","exEn": "This evening I am going to the cinema.","type": "adv","cat": "Days & relative time"},
{"id": 182,"de": "heute Nacht","en": "tonight","ex": "Heute Nacht schlafe ich früh.","exEn": "Tonight I will sleep early.","type": "adv","cat": "Days & relative time"},
{"id": 183,"de": "gestern Morgen","en": "yesterday morning","ex": "Gestern Morgen war ich im Park.","exEn": "Yesterday morning I was in the park.","type": "adv","cat": "Days & relative time"},
{"id": 184,"de": "gestern Abend","en": "yesterday evening","ex": "Gestern Abend habe ich gegessen.","exEn": "Yesterday evening I ate.","type": "adv","cat": "Days & relative time"},
{"id": 185,"de": "gestern Nacht","en": "last night","ex": "Gestern Nacht habe ich gut geschlafen.","exEn": "Last night I slept well.","type": "adv","cat": "Days & relative time"},
{"id": 186,"de": "morgen früh","en": "tomorrow morning","ex": "Morgen früh gehe ich zur Arbeit.","exEn": "Tomorrow morning I will go to work.","type": "adv","cat": "Days & relative time"},
{"id": 187,"de": "morgen Abend","en": "tomorrow evening","ex": "Morgen Abend treffe ich Freunde.","exEn": "Tomorrow evening I will meet friends.","type": "adv","cat": "Days & relative time"},
{"id": 188,"de": "morgen Nacht","en": "tomorrow night","ex": "Morgen Nacht gehe ich früh schlafen.","exEn": "Tomorrow night I will go to sleep early.","type": "adv","cat": "Days & relative time"},
{"id": 189,"de": "der Montag","en": "Monday","ex": "Am Montag beginnt die Woche.","exEn": "On Monday the week begins.","type": "noun","cat": "Days & relative time","art": "der","noun": "Montag","pl": "Montage"},
{"id": 190,"de": "der Dienstag","en": "Tuesday","ex": "Am Dienstag habe ich Unterricht.","exEn": "On Tuesday I have class.","type": "noun","cat": "Days & relative time","art": "der","noun": "Dienstag","pl": "Dienstage"},
{"id": 191,"de": "der Mittwoch","en": "Wednesday","ex": "Am Mittwoch treffe ich Freunde.","exEn": "On Wednesday I meet friends.","type": "noun","cat": "Days & relative time","art": "der","noun": "Mittwoch","pl": "Mittwoche"},
{"id": 192,"de": "der Donnerstag","en": "Thursday","ex": "Am Donnerstag gehe ich einkaufen.","exEn": "On Thursday I go shopping.","type": "noun","cat": "Days & relative time","art": "der","noun": "Donnerstag","pl": "Donnerstage"},
{"id": 193,"de": "der Freitag","en": "Friday","ex": "Am Freitag ist Wochenende.","exEn": "On Friday it's weekend.","type": "noun","cat": "Days & relative time","art": "der","noun": "Freitag","pl": "Freitage"},
{"id": 194,"de": "der Samstag","en": "Saturday","ex": "Am Samstag mache ich nichts.","exEn": "On Saturday I do nothing.","type": "noun","cat": "Days & relative time","art": "der","noun": "Samstag","pl": "Samstage"},
{"id": 195,"de": "der Sonntag","en": "Sunday","ex": "Am Sonntag ruhe ich mich aus.","exEn": "On Sunday I rest.","type": "noun","cat": "Days & relative time","art": "der","noun": "Sonntag","pl": "Sonntage"},
{"id": 196,"de": "das Wochenende","en": "weekend","ex": "Am Wochenende mache ich Urlaub.","exEn": "On the weekend I take a vacation.","type": "noun","cat": "Days & relative time","art": "das","noun": "Wochenende","pl": "Wochenenden"},
{"id": 197,"de": "der Januar","en": "January","ex": "Im Januar ist es kalt.","exEn": "In January it is cold.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Januar"},
{"id": 198,"de": "der Februar","en": "February","ex": "Im Februar schneit es oft.","exEn": "In February it often snows.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Februar"},
{"id": 199,"de": "der März","en": "March","ex": "Im März wird es wärmer.","exEn": "In March it gets warmer.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "März"},
{"id": 200,"de": "der April","en": "April","ex": "Im April blühen die Blumen.","exEn": "In April the flowers bloom.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "April"},
{"id": 201,"de": "der Mai","en": "May","ex": "Im Mai ist es schön.","exEn": "In May it is nice.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Mai"},
{"id": 202,"de": "der Juni","en": "June","ex": "Im Juni ist Sommer.","exEn": "In June it is summer.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Juni"},
{"id": 203,"de": "der Juli","en": "July","ex": "Im Juli ist es heiß.","exEn": "In July it is hot.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Juli"},
{"id": 204,"de": "der August","en": "August","ex": "Im August ist Urlaubszeit.","exEn": "In August it is vacation time.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "August"},
{"id": 205,"de": "der September","en": "September","ex": "Im September beginnt der Herbst.","exEn": "In September autumn begins.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "September"},
{"id": 206,"de": "der Oktober","en": "October","ex": "Im Oktober wird es kälter.","exEn": "In October it gets colder.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Oktober"},
{"id": 207,"de": "der November","en": "November","ex": "Im November ist es kalt.","exEn": "In November it is cold.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "November"},
{"id": 208,"de": "der Dezember","en": "December","ex": "Im Dezember ist Weihnachten.","exEn": "In December it is Christmas.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Dezember"},
{"id": 209,"de": "der Frühling","en": "spring","ex": "Im Frühling blühen die Blumen.","exEn": "In spring the flowers bloom.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Frühling"},
{"id": 210,"de": "der Sommer","en": "summer","ex": "Im Sommer ist es heiß.","exEn": "In summer it is hot.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Sommer"},
{"id": 211,"de": "der Herbst","en": "autumn","ex": "Im Herbst fallen die Blätter.","exEn": "In autumn the leaves fall.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Herbst"},
{"id": 212,"de": "der Winter","en": "winter","ex": "Im Winter schneit es.","exEn": "In winter it snows.","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Winter"},
{"id": 213,"de": "das Datum","en": "date","ex": "Welches Datum ist heute?","exEn": "What date is today?","type": "noun","cat": "Months, seasons & dates","art": "das","noun": "Datum","pl": "Daten"},
{"id": 214,"de": "der Geburtstag","en": "birthday","ex": "Wann ist dein Geburtstag?","exEn": "When is your birthday?","type": "noun","cat": "Months, seasons & dates","art": "der","noun": "Geburtstag","pl": "Geburtstage"},
{"id": 215,"de": "das Alter","en": "age","ex": "Wie alt bist du?","exEn": "How old are you?","type": "noun","cat": "Months, seasons & dates","art": "das","noun": "Alter"},
{"id": 216,"de": "die Uhrzeit","en": "time (clock time)","ex": "Wie spät ist es?","exEn": "What time is it?","type": "noun","cat": "Months, seasons & dates","art": "die","noun": "Uhrzeit","pl": "Uhrzeiten"},
{"id": 217,"de": "die Stunde","en": "hour","ex": "Eine Stunde hat 60 Minuten.","exEn": "An hour has 60 minutes.","type": "noun","cat": "Clock & frequency","art": "die","noun": "Stunde","pl": "Stunden"},
{"id": 218,"de": "die Minute","en": "minute","ex": "Eine Minute hat 60 Sekunden.","exEn": "A minute has 60 seconds.","type": "noun","cat": "Clock & frequency","art": "die","noun": "Minute","pl": "Minuten"},
{"id": 219,"de": "die Sekunde","en": "second","ex": "Eine Sekunde ist sehr kurz.","exEn": "A second is very short.","type": "noun","cat": "Clock & frequency","art": "die","noun": "Sekunde","pl": "Sekunden"},
{"id": 220,"de": "die Viertelstunde","en": "quarter of an hour","ex": "Eine Viertelstunde sind 15 Minuten.","exEn": "A quarter of an hour is 15 minutes.","type": "noun","cat": "Clock & frequency","art": "die","noun": "Viertelstunde","pl": "Viertelstunden"},
{"id": 221,"de": "die halbe Stunde","en": "half an hour","ex": "Eine halbe Stunde sind 30 Minuten.","exEn": "Half an hour is 30 minutes.","type": "noun","cat": "Clock & frequency","art": "die","noun": "halbe Stunde"},
{"id": 222,"de": "der Mittag","en": "noon/midday","ex": "Am Mittag esse ich zu Mittag.","exEn": "At noon I eat lunch.","type": "noun","cat": "Clock & frequency","art": "der","noun": "Mittag","pl": "Mittage"},
{"id": 223,"de": "der Nachmittag","en": "afternoon","ex": "Am Nachmittag mache ich Sport.","exEn": "In the afternoon I do sports.","type": "noun","cat": "Clock & frequency","art": "der","noun": "Nachmittag","pl": "Nachmittage"},
{"id": 224,"de": "der Abend","en": "evening","ex": "Am Abend sehe ich fern.","exEn": "In the evening I watch TV.","type": "noun","cat": "Clock & frequency","art": "der","noun": "Abend","pl": "Abende"},
{"id": 225,"de": "die Mitternacht","en": "midnight","ex": "Um Mitternacht schlafe ich.","exEn": "At midnight I sleep.","type": "noun","cat": "Clock & frequency","art": "die","noun": "Mitternacht"},
{"id": 226,"de": "verspätet","en": "delayed","ex": "Der Zug ist verspätet.","exEn": "The train is delayed.","type": "adv","cat": "Clock & frequency"},
{"id": 227,"de": "rechtzeitig","en": "on time","ex": "Ich komme rechtzeitig.","exEn": "I arrive on time.","type": "adv","cat": "Clock & frequency"},
{"id": 228,"de": "zu spät","en": "too late","ex": "Ich komme zu spät.","exEn": "I arrive too late.","type": "adv","cat": "Clock & frequency"},
{"id": 229,"de": "zu früh","en": "too early","ex": "Ich komme zu früh.","exEn": "I arrive too early.","type": "adv","cat": "Clock & frequency"},
{"id": 230,"de": "gleich","en": "soon/right away","ex": "Ich komme gleich.","exEn": "I'll come right away.","type": "adv","cat": "Clock & frequency"},
{"id": 231,"de": "bald","en": "soon","ex": "Wir sehen uns bald.","exEn": "We'll see each other soon.","type": "adv","cat": "Clock & frequency"},
{"id": 232,"de": "vorher","en": "before","ex": "Ich war vorher hier.","exEn": "I was here before.","type": "adv","cat": "Clock & frequency"},
{"id": 233,"de": "nachher","en": "afterwards","ex": "Wir treffen uns nachher.","exEn": "We'll meet afterwards.","type": "adv","cat": "Clock & frequency"},
{"id": 234,"de": "dann","en": "then","ex": "Dann gehen wir.","exEn": "Then we go.","type": "adv","cat": "Clock & frequency"},
{"id": 235,"de": "danach","en": "after that","ex": "Danach essen wir.","exEn": "After that we eat.","type": "adv","cat": "Clock & frequency"},
{"id": 236,"de": "zuerst","en": "first","ex": "Zuerst trinke ich Kaffee.","exEn": "First I drink coffee.","type": "adv","cat": "Clock & frequency"},
{"id": 237,"de": "zuletzt","en": "last","ex": "Zuletzt gehe ich nach Hause.","exEn": "Last I go home.","type": "adv","cat": "Clock & frequency"},
{"id": 238,"de": "immer","en": "always","ex": "Ich bin immer pünktlich.","exEn": "I am always punctual.","type": "adv","cat": "Clock & frequency"},
{"id": 239,"de": "nie","en": "never","ex": "Ich bin nie zu spät.","exEn": "I am never late.","type": "adv","cat": "Clock & frequency"},
{"id": 240,"de": "manchmal","en": "sometimes","ex": "Manchmal bin ich müde.","exEn": "Sometimes I am tired.","type": "adv","cat": "Clock & frequency"},
{"id": 241,"de": "oft","en": "often","ex": "Ich gehe oft ins Kino.","exEn": "I often go to the cinema.","type": "adv","cat": "Clock & frequency"},
{"id": 242,"de": "selten","en": "rarely","ex": "Ich gehe selten ins Kino.","exEn": "I rarely go to the cinema.","type": "adv","cat": "Clock & frequency"},
{"id": 243,"de": "meistens","en": "mostly","ex": "Meistens bin ich zu Hause.","exEn": "Mostly I am at home.","type": "adv","cat": "Clock & frequency"},
{"id": 244,"de": "normalerweise","en": "normally","ex": "Normalerweise stehe ich früh auf.","exEn": "Normally I get up early.","type": "adv","cat": "Clock & frequency"},
{"id": 245,"de": "gewöhnlich","en": "usually","ex": "Gewöhnlich trinke ich Kaffee.","exEn": "Usually I drink coffee.","type": "adv","cat": "Clock & frequency"},
{"id": 246,"de": "täglich","en": "daily","ex": "Ich gehe täglich zur Arbeit.","exEn": "I go to work daily.","type": "adv","cat": "Clock & frequency"},
{"id": 247,"de": "wöchentlich","en": "weekly","ex": "Ich gehe wöchentlich einkaufen.","exEn": "I go shopping weekly.","type": "adv","cat": "Clock & frequency"},
{"id": 248,"de": "monatlich","en": "monthly","ex": "Ich zahle monatlich Miete.","exEn": "I pay rent monthly.","type": "adv","cat": "Clock & frequency"},
{"id": 249,"de": "jährlich","en": "yearly","ex": "Ich fahre jährlich in Urlaub.","exEn": "I go on vacation yearly.","type": "adv","cat": "Clock & frequency"},
{"id": 250,"de": "stündlich","en": "hourly","ex": "Der Bus fährt stündlich.","exEn": "The bus runs hourly.","type": "adv","cat": "Clock & frequency"},
{"id": 251,"de": "minütlich","en": "every minute","ex": "Die Uhr tickt minütlich.","exEn": "The clock ticks every minute.","type": "adv","cat": "Clock & frequency"},
{"id": 252,"de": "sekündlich","en": "every second","ex": "Die Uhr tickt sekündlich.","exEn": "The clock ticks every second.","type": "adv","cat": "Clock & frequency"}];
window.CATEGORIES = ["Home, people & food", "Time units", "Family, school & work", "Town & places", "Nature & weather", "Colours", "Describing things", "Feelings & states", "Days & relative time", "Months, seasons & dates", "Clock & frequency"];
