# Goethe-Zertifikat A1 word list, F–L. Same format as goethe_a_e.py.
ROWS = [
('fahren', 'to drive / to go (by vehicle)', 'v', 'trav', '', 'Ich fahre mit dem Auto zur Arbeit.', 'I drive to work.'),
('der Fahrer', 'driver', 'n', 'trav', 'Fahrer', 'Bitte nicht mit dem Fahrer sprechen!', 'Please do not talk to the driver!'),
('die Fahrkarte', 'ticket', 'n', 'trav', 'Fahrkarten', 'Hast du schon eine Fahrkarte?', 'Do you already have a ticket?'),
('das Fahrrad', 'bicycle', 'n', 'trav', 'Fahrräder', 'Fährst du mit dem Fahrrad oder mit dem Auto?', 'Are you going by bike or by car?'),
('falsch', 'wrong', 'a', 'desc', '', 'Das ist falsch.', 'That is wrong.'),
('die Familie', 'family', 'n', 'fam', 'Familien', 'Meine Familie lebt in Spanien.', 'My family lives in Spain.'),
('der Familienname', 'surname', 'n', 'per', 'Familiennamen', 'Mein Familienname ist García.', 'My surname is García.'),
('der Familienstand', 'marital status', 'n', 'per', '', 'Bei „Familienstand“ musst du „ledig“ ankreuzen.', 'For "marital status" you have to tick "single".'),
('die Farbe', 'colour', 'n', 'col', 'Farben', 'Die Farbe gefällt mir gut.', 'I like the colour.'),
('das Fax', 'fax', 'n', 'comm', 'Faxe', 'Schicken Sie uns einfach ein Fax!', 'Just send us a fax!'),
('der Feiertag', 'public holiday', 'n', 'free', 'Feiertage', 'Am Montag ist Feiertag.', 'Monday is a public holiday.'),
('der Feierabend', 'end of the working day', 'n', 'work', '', 'Um fünf Uhr habe ich Feierabend.', 'I finish work at five o\'clock.'),
('feiern', 'to celebrate', 'v', 'free', '', 'Wir feiern heute meinen Geburtstag.', 'Today we are celebrating my birthday.'),
('fehlen', 'to be missing / to be absent', 'v', 'verb', '', 'Herr Müller ist nicht da, er fehlt schon seit drei Tagen.', 'Mr Müller is not here; he has been absent for three days.'),
('der Fehler', 'mistake', 'n', 'work', 'Fehler', 'Diesen Fehler mache ich immer.', 'I always make this mistake.'),
('fernsehen', 'to watch TV', 'v', 'free', '', 'Wollen wir heute Abend mal fernsehen?', 'Shall we watch TV tonight?'),
('fertig', 'ready / finished', 'a', 'feel', '', 'Ist mein Auto schon fertig?', 'Is my car ready yet?'),
('das Feuer', 'fire / a light', 'n', 'nat', 'Feuer', 'Haben Sie Feuer?', 'Have you got a light?'),
('das Fieber', 'fever', 'n', 'body', '', 'Mein Mann hat noch immer Fieber.', 'My husband still has a fever.'),
('der Film', 'film', 'n', 'free', 'Filme', 'Ich möchte gern diesen Film sehen.', 'I would like to see this film.'),
('finden', 'to find / to think', 'v', 'verb', '', 'Wir müssen den Schlüssel finden.', 'We have to find the key.'),
('die Firma', 'company', 'n', 'work', 'Firmen', 'Er arbeitet jetzt bei einer anderen Firma.', 'He now works for another company.'),
('die Flasche', 'bottle', 'n', 'food', 'Flaschen', 'Eine Flasche Bier, bitte.', 'A bottle of beer, please.'),
('das Fleisch', 'meat', 'n', 'food', '', 'Fleisch mag ich nicht.', 'I don\'t like meat.'),
('fliegen', 'to fly', 'v', 'trav', '', 'Ich fliege nicht gern. Deshalb fahre ich mit dem Zug.', 'I don\'t like flying. That\'s why I take the train.'),
('abfliegen', 'to take off / to depart (plane)', 'v', 'trav', '', 'Wann fliegst du ab?', 'When does your flight leave?'),
('der Abflug', 'departure (flight)', 'n', 'trav', 'Abflüge', 'Der Abflug ist um 11.20 Uhr.', 'The flight departs at 11.20.'),
('der Flughafen', 'airport', 'n', 'trav', 'Flughäfen', 'Kannst du mich zum Flughafen bringen?', 'Can you take me to the airport?'),
('das Flugzeug', 'aeroplane', 'n', 'trav', 'Flugzeuge', 'Das Flugzeug aus Berlin kommt heute später an.', 'The plane from Berlin arrives later today.'),
('das Formular', 'form', 'n', 'per', 'Formulare', 'Sie müssen dieses Formular ausfüllen.', 'You have to fill in this form.'),
('das Foto', 'photo', 'n', 'free', 'Fotos', 'Darf ich ein Foto machen?', 'May I take a photo?'),
('fragen', 'to ask', 'v', 'verb', '', 'Er möchte Sie etwas fragen.', 'He would like to ask you something.'),
('die Frage', 'question', 'n', 'work', 'Fragen', 'Ich habe eine Frage.', 'I have a question.'),
('die Frau', 'woman / wife / Mrs', 'n', 'fam', 'Frauen', 'Guten Tag, Frau Schmitt!', 'Good day, Mrs Schmitt!'),
('frei', 'free / vacant', 'a', 'desc', '', 'Ist der Platz noch frei?', 'Is this seat still free?'),
('die Freizeit', 'free time', 'n', 'free', '', 'In meiner Freizeit spiele ich oft Fußball.', 'In my free time I often play football.'),
('fremd', 'foreign / strange', 'a', 'geo', '', 'Das weiß ich nicht; ich bin fremd hier.', 'I don\'t know; I\'m not from here.'),
('sich freuen', 'to be happy / to look forward to', 'v', 'feel', '', 'Ich freue mich auf den Urlaub.', 'I am looking forward to the holiday.'),
('der Freund', 'friend / boyfriend', 'n', 'fam', 'Freunde', 'Das ist ein Freund von mir.', 'That is a friend of mine.'),
('früher', 'earlier / in the past', 'd', 'time', '', 'Früher waren wir oft zusammen im Kino.', 'In the past we often went to the cinema together.'),
('frühstücken', 'to have breakfast', 'v', 'food', '', 'Am Sonntag frühstücke ich gern im Bett.', 'On Sundays I like having breakfast in bed.'),
('das Frühstück', 'breakfast', 'n', 'food', '', 'Möchtest du ein Ei zum Frühstück?', 'Would you like an egg for breakfast?'),
('die Führung', 'guided tour', 'n', 'free', 'Führungen', 'Die Führung durch das Haus beginnt in drei Minuten.', 'The guided tour of the house starts in three minutes.'),
('für', 'for', 'w', 'small', '', 'Das ist für Sie.', 'This is for you.'),
('der Fuß', 'foot', 'n', 'body', 'Füße', 'Der linke Fuß tut mir weh.', 'My left foot hurts.'),
('zu Fuß', 'on foot', 'p', 'trav', '', 'Ich gehe zu Fuß.', 'I am walking.'),
('der Fußball', 'football', 'n', 'free', 'Fußbälle', 'Spielt ihr gerne Fußball?', 'Do you like playing football?'),
('der Garten', 'garden', 'n', 'home', 'Gärten', 'Wir haben leider keinen Garten.', 'Unfortunately we don\'t have a garden.'),
('der Gast', 'guest', 'n', 'free', 'Gäste', 'Am Wochenende haben wir mehrere Gäste.', 'At the weekend we have several guests.'),
('geben', 'to give', 'v', 'verb', '', 'Kannst du mir bitte deinen Kugelschreiber geben?', 'Can you give me your pen, please?'),
('es gibt', 'there is / there are', 'p', 'small', '', 'Es gibt keine Karten mehr.', 'There are no tickets left.'),
('geboren', 'born', 'a', 'per', '', 'Ich bin in Zagreb geboren.', 'I was born in Zagreb.'),
('das Geburtsjahr', 'year of birth', 'n', 'per', 'Geburtsjahre', 'Das Geburtsjahr Ihres Sohnes, bitte?', 'Your son\'s year of birth, please?'),
('der Geburtsort', 'place of birth', 'n', 'per', 'Geburtsorte', 'Bitte schreiben Sie Ihren Geburtsort auf das Formular.', 'Please write your place of birth on the form.'),
('der Geburtstag', 'birthday', 'n', 'free', 'Geburtstage', 'Herzlichen Glückwunsch zum Geburtstag!', 'Happy birthday!'),
('gefallen', 'to please / to like', 'v', 'feel', '', 'Das gefällt mir.', 'I like that.'),
('gegen', 'against / around (time)', 'w', 'small', '', 'Wer spielt gegen wen?', 'Who is playing against whom?'),
('gehen', 'to go / to walk', 'v', 'verb', '', 'Ich muss zum Arzt gehen.', 'I have to go to the doctor.'),
('Wie geht\'s?', 'How are you?', 'p', 'small', '', 'Hallo Anna! Wie geht\'s?', 'Hello Anna! How are you?'),
('gehören', 'to belong to', 'v', 'verb', '', 'Wem gehört das?', 'Who does that belong to?'),
('das Geld', 'money', 'n', 'shop', 'Gelder', 'Hast du noch Geld?', 'Do you have any money left?'),
('das Gepäck', 'luggage', 'n', 'trav', '', 'Wollen Sie Ihr Gepäck mitnehmen?', 'Do you want to take your luggage with you?'),
('gerade', 'just / right now', 'd', 'time', '', 'Da kommt er ja gerade.', 'Here he comes right now.'),
('geradeaus', 'straight ahead', 'd', 'town', '', 'Gehen Sie immer geradeaus!', 'Keep going straight ahead!'),
('gern', 'gladly / to like doing', 'd', 'feel', '', 'Ich gehe gerne einkaufen.', 'I like going shopping.'),
('das Geschäft', 'shop / business', 'n', 'shop', 'Geschäfte', 'Die Geschäfte schließen um 18.30 Uhr.', 'The shops close at 6.30 p.m.'),
('das Geschenk', 'present / gift', 'n', 'free', 'Geschenke', 'Danke für das schöne Geschenk.', 'Thank you for the lovely present.'),
('die Geschwister', 'siblings (plural)', 'n', 'fam', '', 'Ich habe leider keine Geschwister.', 'Unfortunately I have no brothers or sisters.'),
('das Gespräch', 'conversation / talk', 'n', 'comm', 'Gespräche', 'Das Gespräch mit Frau Kunz ist um 14 Uhr.', 'The meeting with Ms Kunz is at 2 p.m.'),
('gestern', 'yesterday', 'd', 'time', '', 'Gestern war ich krank.', 'Yesterday I was sick.'),
('gestorben', 'died / dead', 'a', 'per', '', 'Ihr Großvater ist letztes Jahr gestorben.', 'Her grandfather died last year.'),
('das Getränk', 'drink', 'n', 'food', 'Getränke', 'Mein Lieblingsgetränk ist Tomatensaft.', 'My favourite drink is tomato juice.'),
('das Gewicht', 'weight', 'n', 'num', 'Gewichte', 'Bei „Gewicht“ schreibst du: 62 Kilo.', 'For "weight" you write: 62 kilos.'),
('gewinnen', 'to win', 'v', 'free', '', 'Wer gewinnt das Spiel?', 'Who is winning the game?'),
('das Glas', 'glass', 'n', 'food', 'Gläser', 'Bitte noch ein Glas Wein!', 'Another glass of wine, please!'),
('glauben', 'to believe / to think', 'v', 'verb', '', 'Ich glaube, er kommt gleich.', 'I think he will be here soon.'),
('gleich', 'soon / same', 'd', 'time', '', 'Das ist der gleiche Preis.', 'That is the same price.'),
('das Gleis', 'platform / track', 'n', 'trav', 'Gleise', 'Der ICE nach Berlin hält heute an Gleis 12.', 'The ICE to Berlin stops at platform 12 today.'),
('das Glück', 'luck / happiness', 'n', 'feel', '', 'Viel Glück!', 'Good luck!'),
('glücklich', 'happy', 'a', 'feel', '', 'Meine Kinder sind glücklich verheiratet.', 'My children are happily married.'),
('der Glückwunsch', 'congratulations', 'n', 'free', 'Glückwünsche', 'Herzlichen Glückwunsch zum Geburtstag.', 'Happy birthday.'),
('das Grad', 'degree', 'n', 'nat', 'Grad', 'Heute haben wir dreißig Grad.', 'It is thirty degrees today.'),
('gratulieren', 'to congratulate', 'v', 'free', '', 'Ich gratuliere dir!', 'Congratulations!'),
('grillen', 'to grill / to barbecue', 'v', 'food', '', 'Heute grillen wir im Garten.', 'Today we are having a barbecue in the garden.'),
('groß', 'big / tall', 'a', 'desc', '', 'Mein Bruder und ich sind gleich groß.', 'My brother and I are the same height.'),
('die Größe', 'size / height', 'n', 'shop', 'Größen', 'Haben Sie das auch in Größe 40?', 'Do you have this in size 40 as well?'),
('die Großeltern', 'grandparents (plural)', 'n', 'fam', '', 'Meine Großeltern leben in Japan.', 'My grandparents live in Japan.'),
('die Großmutter', 'grandmother', 'n', 'fam', 'Großmütter', 'Meine Großmutter heißt Eva.', 'My grandmother is called Eva.'),
('der Großvater', 'grandfather', 'n', 'fam', 'Großväter', 'Mein Großvater ist schon 80.', 'My grandfather is already 80.'),
('die Gruppe', 'group', 'n', 'work', 'Gruppen', 'Die erste Gruppe beginnt um 16 Uhr.', 'The first group starts at 4 p.m.'),
('der Gruß', 'greeting', 'n', 'comm', 'Grüße', 'Viele Grüße an Ihre Frau.', 'Best wishes to your wife.'),
('gültig', 'valid', 'a', 'per', '', 'Der Pass ist nicht mehr gültig.', 'The passport is no longer valid.'),
('günstig', 'cheap / good value', 'a', 'shop', '', 'Dort gibt es günstige Angebote.', 'There are good deals there.'),
('gut', 'good / well', 'a', 'desc', '', 'Das finde ich gut.', 'I think that\'s good.'),
('das Haar', 'hair', 'n', 'body', 'Haare', 'Sie hat lange Haare.', 'She has long hair.'),
('haben', 'to have', 'v', 'verb', '', 'Ich habe ein neues Auto.', 'I have a new car.'),
('das Hähnchen', 'chicken (food)', 'n', 'food', 'Hähnchen', 'Ein Hähnchen mit Pommes, bitte!', 'A chicken with chips, please!'),
('die Halbpension', 'half board', 'n', 'trav', '', 'Möchten Sie Vollpension oder Halbpension?', 'Would you like full board or half board?'),
('die Halle', 'hall', 'n', 'town', 'Hallen', 'Wir treffen uns in Halle B.', 'We will meet in hall B.'),
('halten', 'to stop / to hold', 'v', 'trav', '', 'Dieser Zug hält nicht in Rüdesheim.', 'This train does not stop in Rüdesheim.'),
('die Haltestelle', 'bus / tram stop', 'n', 'trav', 'Haltestellen', 'An der nächsten Haltestelle müssen Sie aussteigen.', 'You have to get off at the next stop.'),
('die Hand', 'hand', 'n', 'body', 'Hände', 'Er gibt mir die Hand.', 'He shakes my hand.'),
('das Handy', 'mobile phone', 'n', 'comm', 'Handys', 'In der Schule bitte die Handys ausmachen!', 'Please switch off your phones at school!'),
('das Haus', 'house', 'n', 'home', 'Häuser', 'In welchem Haus wohnst du?', 'Which house do you live in?'),
('nach Hause', '(to) home', 'p', 'home', '', 'Ich gehe jetzt nach Hause.', 'I am going home now.'),
('zu Hause', 'at home', 'p', 'home', '', 'Paul ist nicht zu Hause.', 'Paul is not at home.'),
('die Hausaufgabe', 'homework', 'n', 'work', 'Hausaufgaben', 'Kannst du mir bei den Hausaufgaben helfen?', 'Can you help me with my homework?'),
('die Hausfrau', 'housewife', 'n', 'work', 'Hausfrauen', 'Die Hausfrau wäscht, kocht und kauft ein.', 'The housewife does the washing, cooking and shopping.'),
('der Hausmann', 'househusband', 'n', 'work', 'Hausmänner', 'Der Hausmann wäscht, kocht und kauft ein.', 'The househusband does the washing, cooking and shopping.'),
('die Heimat', 'home country / homeland', 'n', 'geo', '', 'Ich komme aus der Schweiz. Das ist meine Heimat.', 'I come from Switzerland. That is my homeland.'),
('heiraten', 'to marry', 'v', 'fam', '', 'Meine Schwester heiratet einen Japaner.', 'My sister is marrying a Japanese man.'),
('heißen', 'to be called', 'v', 'per', '', 'Ich heiße Charlotte Meier.', 'My name is Charlotte Meier.'),
('helfen', 'to help', 'v', 'verb', '', 'Können Sie mir helfen, bitte?', 'Can you help me, please?'),
('hell', 'bright / light', 'a', 'desc', '', 'Im Sommer ist es bis 21 Uhr hell.', 'In summer it is light until 9 p.m.'),
('der Herd', 'cooker / stove', 'n', 'home', 'Herde', 'In der neuen Küche fehlt noch der Herd.', 'The new kitchen still has no cooker.'),
('der Herr', 'gentleman / Mr', 'n', 'per', 'Herren', 'Guten Tag, Herr Sommer!', 'Good day, Mr Sommer!'),
('herzlich', 'warm / sincere', 'a', 'feel', '', 'Herzlichen Glückwunsch!', 'Congratulations!'),
('heute', 'today', 'd', 'time', '', 'Heute ist ein schöner Tag.', 'Today is a beautiful day.'),
('hier', 'here', 'w', 'small', '', 'Hier wohne ich.', 'I live here.'),
('die Hilfe', 'help', 'n', 'small', '', 'Brauchen Sie meine Hilfe?', 'Do you need my help?'),
('hinten', 'at the back', 'd', 'small', '', 'Die Tür zum Aussteigen ist hinten.', 'The exit door is at the back.'),
('das Hobby', 'hobby', 'n', 'free', 'Hobbys', 'Meine Hobbys sind Wandern und Schwimmen.', 'My hobbies are hiking and swimming.'),
('hoch', 'high / tall', 'a', 'desc', '', 'Der Mount Everest ist 8.848 Meter hoch.', 'Mount Everest is 8,848 metres high.'),
('die Hochzeit', 'wedding', 'n', 'free', 'Hochzeiten', 'Zu dieser Hochzeit kommen mehr als fünfzig Gäste.', 'More than fifty guests are coming to this wedding.'),
('holen', 'to fetch / to get', 'v', 'verb', '', 'Ich hole zwei Flaschen Wasser aus der Küche.', 'I\'ll fetch two bottles of water from the kitchen.'),
('hören', 'to hear / to listen', 'v', 'verb', '', 'Ich habe das Lied schon mal gehört.', 'I have heard the song before.'),
('das Hotel', 'hotel', 'n', 'trav', 'Hotels', 'Im Urlaub sind wir in einem Hotel am Meer.', 'On holiday we stay in a hotel by the sea.'),
('der Hund', 'dog', 'n', 'nat', 'Hunde', 'Der Hund ist noch jung.', 'The dog is still young.'),
('der Hunger', 'hunger', 'n', 'food', '', 'Ich habe Hunger! Wann ist das Essen fertig?', 'I\'m hungry! When is the food ready?'),
('ich', 'I', 'w', 'small', '', 'Ich heiße Veronika.', 'My name is Veronika.'),
('ihm', 'to him (dative)', 'w', 'small', '', 'Gib ihm bitte das Buch.', 'Please give him the book.'),
('ihn', 'him (accusative)', 'w', 'small', '', 'Ruf ihn bitte an.', 'Please call him.'),
('ihr', 'you (plural) / her / their', 'w', 'small', '', 'Gib ihr bitte das Buch.', 'Please give her the book.'),
('immer', 'always', 'd', 'time', '', 'Frau Bast kommt immer zu spät.', 'Ms Bast always arrives late.'),
('in', 'in / into', 'w', 'small', '', 'Der Zug kommt in fünf Minuten.', 'The train comes in five minutes.'),
('die Information', 'information / information desk', 'n', 'trav', 'Informationen', 'Wenn Sie Fragen haben, gehen Sie zur Information.', 'If you have questions, go to the information desk.'),
('international', 'international', 'a', 'geo', '', 'Unser Deutschkurs ist international.', 'Our German course is international.'),
('das Internet', 'internet', 'n', 'comm', '', 'Das findest du im Internet.', 'You can find that on the internet.'),
('ja', 'yes', 'p', 'small', '', 'Sind Sie Herr Watanabe? – Ja.', 'Are you Mr Watanabe? – Yes.'),
('die Jacke', 'jacket', 'n', 'shop', 'Jacken', 'Zieh dir eine Jacke an. Es ist kalt.', 'Put on a jacket. It\'s cold.'),
('jeder', 'every / each', 'w', 'small', '', 'Blumen kannst du in jedem Bahnhof kaufen.', 'You can buy flowers at every station.'),
('jetzt', 'now', 'd', 'time', '', 'Jetzt machen wir eine Pause.', 'Now we are taking a break.'),
('der Job', 'job', 'n', 'work', 'Jobs', 'Jenny hat einen neuen Job bei der Post.', 'Jenny has a new job at the post office.'),
('der Jugendliche', 'young person / teenager', 'n', 'fam', 'Jugendlichen', 'Viele Jugendliche kaufen gern ein.', 'Many young people like shopping.'),
('jung', 'young', 'a', 'desc', '', 'Claudia ist 21. – Was? Noch so jung?', 'Claudia is 21. – What? Still so young?'),
('der Junge', 'boy', 'n', 'fam', 'Jungen', 'Ich habe zwei Kinder. Einen Jungen und ein Mädchen.', 'I have two children. A boy and a girl.'),
('der Kaffee', 'coffee', 'n', 'food', '', 'Zum Frühstück trinke ich immer Kaffee.', 'I always drink coffee for breakfast.'),
('kaputt', 'broken', 'a', 'desc', '', 'Das Glas war teuer. Es geht sehr leicht kaputt.', 'The glass was expensive. It breaks very easily.'),
('die Karte', 'card / ticket / menu / map', 'n', 'shop', 'Karten', 'Ich schreibe meinen Bekannten eine Karte aus dem Urlaub.', 'I write my friends a postcard from my holiday.'),
('die Kreditkarte', 'credit card', 'n', 'shop', 'Kreditkarten', 'Kann ich auch mit Karte bezahlen?', 'Can I pay by card too?'),
('die Kartoffel', 'potato', 'n', 'food', 'Kartoffeln', 'Für Pommes frites braucht man Kartoffeln.', 'You need potatoes for chips.'),
('die Kasse', 'checkout / till', 'n', 'shop', 'Kassen', 'Zahlen Sie bitte an der Kasse.', 'Please pay at the checkout.'),
('kaufen', 'to buy', 'v', 'shop', '', 'Tim kauft sich ein neues Auto.', 'Tim is buying himself a new car.'),
('kein', 'no / not a', 'w', 'small', '', 'Es gibt keine Eintrittskarten mehr.', 'There are no more tickets.'),
('kennen', 'to know (be familiar with)', 'v', 'verb', '', 'Kennen Sie diese Frau? – Nein, leider nicht.', 'Do you know this woman? – No, unfortunately not.'),
('kennenlernen', 'to get to know', 'v', 'verb', '', 'Wir sind neu hier. Wir möchten Sie kennenlernen.', 'We are new here. We would like to get to know you.'),
('das Kind', 'child', 'n', 'fam', 'Kinder', 'Wie viele Kinder haben Sie?', 'How many children do you have?'),
('der Kindergarten', 'kindergarten', 'n', 'fam', 'Kindergärten', 'Die kleine Laura geht schon in den Kindergarten.', 'Little Laura already goes to kindergarten.'),
('das Kino', 'cinema', 'n', 'free', 'Kinos', 'Wir sehen heute Abend im Kino einen schönen Film.', 'Tonight we are seeing a nice film at the cinema.'),
('der Kiosk', 'kiosk', 'n', 'shop', 'Kioske', 'Am Kiosk bekommen Sie Getränke und Zeitungen.', 'You can get drinks and newspapers at the kiosk.'),
('klar', 'clear / of course', 'a', 'desc', '', 'Kommst du mit? – Klar!', 'Are you coming? – Of course!'),
('die Klasse', 'class', 'n', 'work', 'Klassen', 'In unserer Klasse sind fünfundzwanzig Schüler.', 'There are twenty-five pupils in our class.'),
('die Kleidung', 'clothes', 'n', 'shop', '', 'Wo finde ich Kleidung?', 'Where can I find clothes?'),
('klein', 'small', 'a', 'desc', '', 'Eltville ist eine kleine Stadt am Rhein.', 'Eltville is a small town on the Rhine.'),
('kochen', 'to cook', 'v', 'food', '', 'Herr Georgi kann gut kochen.', 'Mr Georgi is a good cook.'),
('der Koffer', 'suitcase', 'n', 'trav', 'Koffer', 'Ist das Ihr Koffer?', 'Is that your suitcase?'),
('der Kollege', 'colleague (male)', 'n', 'work', 'Kollegen', 'Das ist mein Kollege Peter.', 'This is my colleague Peter.'),
('die Kollegin', 'colleague (female)', 'n', 'work', 'Kolleginnen', 'Wie heißt die neue Kollegin?', 'What is the new colleague\'s name?'),
('kommen', 'to come', 'v', 'verb', '', 'Woher kommen Sie? – Aus Frankreich.', 'Where are you from? – From France.'),
('können', 'can / to be able to', 'v', 'verb', '', 'Können Sie mir helfen?', 'Can you help me?'),
('das Konto', 'bank account', 'n', 'shop', 'Konten', 'Das Geld überweisen wir am ersten März auf Ihr Konto.', 'We will transfer the money to your account on the first of March.'),
('der Kopf', 'head', 'n', 'body', 'Köpfe', 'Mein Kopf tut weh!', 'My head hurts!'),
('kosten', 'to cost', 'v', 'shop', '', 'Wie viel kostet das? – 10 Euro.', 'How much does that cost? – 10 euros.'),
('krank', 'sick / ill', 'a', 'body', '', 'Ich kann heute nicht zur Arbeit kommen, ich bin krank.', 'I can\'t come to work today, I\'m sick.'),
('kriegen', 'to get (informal)', 'v', 'verb', '', 'Ich kriege 15 Euro in der Stunde für meine Arbeit.', 'I get 15 euros an hour for my work.'),
('die Küche', 'kitchen', 'n', 'home', 'Küchen', 'Der neue Herd kommt in die Küche.', 'The new cooker goes in the kitchen.'),
('der Kuchen', 'cake', 'n', 'food', 'Kuchen', 'Möchtest du ein Stück Kuchen?', 'Would you like a piece of cake?'),
('der Kugelschreiber', 'ballpoint pen', 'n', 'work', 'Kugelschreiber', 'Hast du einen Kugelschreiber für mich?', 'Do you have a pen for me?'),
('der Kühlschrank', 'fridge', 'n', 'home', 'Kühlschränke', 'Haben wir noch Milch? – Ja, im Kühlschrank.', 'Do we still have milk? – Yes, in the fridge.'),
('kulturell', 'cultural', 'a', 'free', '', 'Ich bin kulturell interessiert. Ich gehe oft ins Museum.', 'I am interested in culture. I often go to the museum.'),
('sich kümmern', 'to take care of', 'v', 'fam', '', 'Jede Mutter kümmert sich um ihre kleinen Kinder.', 'Every mother takes care of her small children.'),
('der Kunde', 'customer (male)', 'n', 'shop', 'Kunden', 'Der Kunde möchte bezahlen.', 'The customer wants to pay.'),
('die Kundin', 'customer (female)', 'n', 'shop', 'Kundinnen', 'Einen Moment, bitte. Ich habe eine Kundin.', 'One moment, please. I have a customer.'),
('der Kurs', 'course', 'n', 'work', 'Kurse', 'Der Deutschkurs geht bis zum Sommer.', 'The German course runs until summer.'),
('kurz', 'short', 'a', 'desc', '', 'Ricardo hat kurzes Haar.', 'Ricardo has short hair.'),
('lachen', 'to laugh', 'v', 'feel', '', 'Die Kinder lachen viel.', 'The children laugh a lot.'),
('der Laden', 'shop', 'n', 'shop', 'Läden', 'Im Buchladen können Sie Bücher kaufen.', 'You can buy books in the bookshop.'),
('das Land', 'country / countryside', 'n', 'geo', 'Länder', 'Italien ist ein schönes Land.', 'Italy is a beautiful country.'),
('lang', 'long', 'a', 'desc', '', 'Die Jeans ist zu lang.', 'The jeans are too long.'),
('lange', 'for a long time', 'd', 'time', '', 'Wie lange fährt der Zug von Hamburg nach Berlin?', 'How long does the train take from Hamburg to Berlin?'),
('langsam', 'slow / slowly', 'a', 'desc', '', 'Könnten Sie bitte etwas langsamer sprechen?', 'Could you please speak a bit more slowly?'),
('laufen', 'to run / to walk', 'v', 'verb', '', 'Ich möchte nicht Auto fahren, ich möchte laufen.', 'I don\'t want to drive, I want to walk.'),
('laut', 'loud', 'a', 'desc', '', 'Nicht so laut! Das Baby schläft.', 'Not so loud! The baby is sleeping.'),
('leben', 'to live', 'v', 'verb', '', 'Sie lebt bei ihrer Schwester.', 'She lives with her sister.'),
('das Leben', 'life', 'n', 'feel', 'Leben', 'Das Leben in diesem Land ist teuer.', 'Life in this country is expensive.'),
('die Lebensmittel', 'groceries (plural)', 'n', 'shop', '', 'Lebensmittel bekommen Sie im Supermarkt.', 'You can get groceries at the supermarket.'),
('ledig', 'single (not married)', 'a', 'per', '', 'Sind Sie verheiratet? – Nein. Ledig.', 'Are you married? – No. Single.'),
('legen', 'to put / to lay', 'v', 'verb', '', 'Legen Sie das Buch auf den Tisch.', 'Put the book on the table.'),
('der Lehrer', 'teacher (male)', 'n', 'work', 'Lehrer', 'Der Lehrer erklärt die Aufgabe.', 'The teacher explains the task.'),
('die Lehrerin', 'teacher (female)', 'n', 'work', 'Lehrerinnen', 'Unsere Deutschlehrerin heißt Frau Müller.', 'Our German teacher is called Ms Müller.'),
('leicht', 'easy / light', 'a', 'desc', '', 'Deutsch ist nicht leicht.', 'German is not easy.'),
('leider', 'unfortunately', 'd', 'feel', '', 'Leider kann ich nicht kommen. Ich muss zum Arzt.', 'Unfortunately I can\'t come. I have to go to the doctor.'),
('leise', 'quiet / quietly', 'a', 'desc', '', 'Seid leise. Die anderen schlafen schon.', 'Be quiet. The others are already asleep.'),
('lernen', 'to learn', 'v', 'work', '', 'Wie lange lernen Sie schon Deutsch?', 'How long have you been learning German?'),
('lesen', 'to read', 'v', 'free', '', 'Ich lese ein Buch von García Márquez.', 'I am reading a book by García Márquez.'),
('letzter', 'last', 'a', 'time', '', 'Morgen ist der letzte Kurstag.', 'Tomorrow is the last day of the course.'),
('die Leute', 'people (plural)', 'n', 'fam', '', 'In der Disco sind viele Leute.', 'There are a lot of people at the club.'),
('das Licht', 'light', 'n', 'home', 'Lichter', 'Wo macht man hier das Licht an?', 'Where do you switch on the light here?'),
('lieb', 'dear / kind', 'a', 'feel', '', 'Liebe Susanne, lieber Hans, …', 'Dear Susanne, dear Hans, …'),
('lieben', 'to love', 'v', 'feel', '', 'Ich liebe dich!', 'I love you!'),
('lieber', 'rather / prefer', 'd', 'feel', '', 'Sie fährt lieber mit der Bahn.', 'She prefers to go by train.'),
('Lieblings-', 'favourite …', 'w', 'feel', '', 'Mein Lieblingsfilm ist „Schwarze Augen“.', 'My favourite film is "Black Eyes".'),
('das Lied', 'song', 'n', 'free', 'Lieder', 'Welches ist dein Lieblingslied?', 'Which is your favourite song?'),
('liegen', 'to lie / to be located', 'v', 'verb', '', 'Frankfurt liegt am Main.', 'Frankfurt is on the river Main.'),
('links', 'left', 'd', 'town', '', 'Gehen Sie die nächste Straße links.', 'Take the next street on the left.'),
('der Lkw', 'lorry / truck', 'n', 'trav', 'Lkws', 'Dieser Lkw ist sehr groß.', 'This lorry is very big.'),
('das Lokal', 'restaurant / pub', 'n', 'town', 'Lokale', 'In unserer Straße gibt es ein neues Lokal.', 'There is a new restaurant in our street.'),
('die Lösung', 'solution', 'n', 'work', 'Lösungen', 'Die Lösung ist ganz einfach.', 'The solution is quite simple.'),
('lustig', 'funny / fun', 'a', 'feel', '', 'Frau Mertens ist lustig. Sie lacht immer.', 'Ms Mertens is funny. She is always laughing.'),
]
