# Goethe-Zertifikat A1 word list, S–Z, plus the word groups (numbers, colours,
# directions, measures, parts of the day). Same format as goethe_a_e.py.
ROWS = [
('der Saft', 'juice', 'n', 'food', 'Säfte', 'Möchtest du einen Apfelsaft?', 'Would you like an apple juice?'),
('sagen', 'to say', 'v', 'verb', '', 'Sag mal, wie geht es dir denn?', 'Tell me, how are you?'),
('der Salat', 'salad / lettuce', 'n', 'food', 'Salate', 'Wie schmeckt dir der Salat?', 'How do you like the salad?'),
('das Salz', 'salt', 'n', 'food', '', 'Entschuldigung, kann ich bitte Salz haben?', 'Excuse me, can I have some salt, please?'),
('der Satz', 'sentence', 'n', 'work', 'Sätze', 'Dieser Satz ist sehr einfach.', 'This sentence is very simple.'),
('die S-Bahn', 'suburban train', 'n', 'trav', 'S-Bahnen', 'Ich nehme lieber die S-Bahn.', 'I\'d rather take the suburban train.'),
('der Schalter', 'counter / switch', 'n', 'trav', 'Schalter', 'Gehen Sie bitte zum Schalter drei!', 'Please go to counter three!'),
('scheinen', 'to shine', 'v', 'nat', '', 'Die Sonne scheint.', 'The sun is shining.'),
('schicken', 'to send', 'v', 'comm', '', 'Bitte schicken Sie mir eine E-Mail.', 'Please send me an email.'),
('das Schild', 'sign', 'n', 'town', 'Schilder', 'Haben Sie nicht das Schild gesehen?', 'Didn\'t you see the sign?'),
('der Schinken', 'ham', 'n', 'food', 'Schinken', 'Ich möchte gern ein Schinkenbrot.', 'I would like a ham sandwich.'),
('schlafen', 'to sleep', 'v', 'verb', '', 'Ich schlafe meistens acht Stunden.', 'I usually sleep eight hours.'),
('schlecht', 'bad', 'a', 'desc', '', 'Wir haben schlechtes Wetter.', 'We have bad weather.'),
('schließen', 'to close', 'v', 'verb', '', 'Bitte schließen Sie die Tür.', 'Please close the door.'),
('geschlossen', 'closed', 'a', 'shop', '', 'Die Bank hat am Samstag geschlossen.', 'The bank is closed on Saturdays.'),
('der Schluss', 'end', 'n', 'time', 'Schlüsse', 'Ich muss jetzt Schluss machen.', 'I have to stop now.'),
('der Schlüssel', 'key', 'n', 'home', 'Schlüssel', 'Ich gebe Ihnen noch den Zimmerschlüssel.', 'Here is your room key.'),
('schmecken', 'to taste', 'v', 'food', '', 'Schmeckt das gut?', 'Does that taste good?'),
('schnell', 'fast / quick', 'a', 'desc', '', 'Er fährt schnell.', 'He drives fast.'),
('schon', 'already', 'd', 'time', '', 'Ist das Essen schon fertig?', 'Is the food ready already?'),
('schön', 'beautiful / nice', 'a', 'desc', '', 'Schönen Urlaub!', 'Have a nice holiday!'),
('der Schrank', 'cupboard / wardrobe', 'n', 'home', 'Schränke', 'Die Gläser stehen im Schrank.', 'The glasses are in the cupboard.'),
('schreiben', 'to write', 'v', 'work', '', 'Ich schreibe meiner Mutter eine Karte.', 'I am writing my mother a card.'),
('der Schuh', 'shoe', 'n', 'shop', 'Schuhe', 'Zieh die Schuhe aus!', 'Take your shoes off!'),
('die Schule', 'school', 'n', 'work', 'Schulen', 'Meine Tochter geht schon in die Schule.', 'My daughter already goes to school.'),
('der Schüler', 'pupil (male)', 'n', 'work', 'Schüler', 'In meinem Kurs sind fünf Schüler.', 'There are five pupils in my course.'),
('die Schülerin', 'pupil (female)', 'n', 'work', 'Schülerinnen', 'In meinem Kurs sind acht Schülerinnen.', 'There are eight female pupils in my course.'),
('schwer', 'heavy / difficult', 'a', 'desc', '', 'Ist Ihr Gepäck sehr schwer?', 'Is your luggage very heavy?'),
('die Schwester', 'sister', 'n', 'fam', 'Schwestern', 'Meine Schwester kommt am Dienstag.', 'My sister is coming on Tuesday.'),
('schwimmen', 'to swim', 'v', 'free', '', 'Ich schwimme jeden Tag einen Kilometer.', 'I swim a kilometre every day.'),
('das Schwimmbad', 'swimming pool', 'n', 'free', 'Schwimmbäder', 'Kommst du mit ins Schwimmbad?', 'Are you coming to the swimming pool?'),
('der See', 'lake', 'n', 'nat', 'Seen', 'Komm, wir fahren zum Starnberger See.', 'Come on, let\'s drive to Lake Starnberg.'),
('sehen', 'to see', 'v', 'verb', '', 'Ich kann dich nicht sehen.', 'I can\'t see you.'),
('die Sehenswürdigkeit', 'sight / tourist attraction', 'n', 'trav', 'Sehenswürdigkeiten', 'Welche Sehenswürdigkeiten gibt es in Frankfurt?', 'What sights are there in Frankfurt?'),
('sehr', 'very', 'w', 'small', '', 'Das ist sehr schwer.', 'That is very difficult.'),
('sein', 'to be', 'v', 'verb', '', 'Ich bin dreiundzwanzig.', 'I am twenty-three.'),
('sein (Pronomen)', 'his', 'w', 'small', '', 'Herr Müller ist in seinem Zimmer.', 'Mr Müller is in his room.'),
('weg sein', 'to be gone / away', 'v', 'verb', '', 'Herr Meier ist schon weg.', 'Mr Meier has already left.'),
('zu sein', 'to be closed', 'v', 'home', '', 'Die Tür ist zu.', 'The door is closed.'),
('seit', 'since / for (time)', 'w', 'small', '', 'Ich wohne seit drei Jahren in Köln.', 'I have lived in Cologne for three years.'),
('selbstständig', 'self-employed / independent', 'a', 'work', '', 'Er ist selbstständig.', 'He is self-employed.'),
('sich', 'oneself / himself / herself', 'w', 'small', '', 'Sie müssen sich erst anmelden.', 'You have to register first.'),
('sie', 'she / they', 'w', 'small', '', 'Wie heißt sie?', 'What is her name?'),
('Sie', 'you (formal)', 'w', 'small', '', 'Wie heißen Sie, bitte?', 'What is your name, please?'),
('sitzen', 'to sit', 'v', 'verb', '', 'Wo sitzen Sie?', 'Where are you sitting?'),
('so', 'so / like this', 'w', 'small', '', 'Fahren Sie bitte nicht so schnell!', 'Please don\'t drive so fast!'),
('das Sofa', 'sofa', 'n', 'home', 'Sofas', 'Das Sofa ist neu.', 'The sofa is new.'),
('sofort', 'immediately', 'd', 'time', '', 'Bitte antworten Sie sofort.', 'Please answer immediately.'),
('der Sohn', 'son', 'n', 'fam', 'Söhne', 'Das ist Hans, mein Sohn.', 'This is Hans, my son.'),
('sollen', 'should / to be supposed to', 'v', 'verb', '', 'Was soll ich mitbringen?', 'What should I bring?'),
('die Sonne', 'sun', 'n', 'nat', 'Sonnen', 'Die Sonne scheint.', 'The sun is shining.'),
('spät', 'late', 'a', 'time', '', 'Es ist schon spät, ich muss gehen.', 'It\'s already late, I have to go.'),
('später', 'later', 'd', 'time', '', 'Das können wir später machen.', 'We can do that later.'),
('die Speisekarte', 'menu', 'n', 'food', 'Speisekarten', 'Bringen Sie mir die Speisekarte, bitte.', 'Bring me the menu, please.'),
('spielen', 'to play', 'v', 'free', '', 'Die Kinder spielen draußen.', 'The children are playing outside.'),
('der Sport', 'sport', 'n', 'free', '', 'Ich mache viel Sport.', 'I do a lot of sport.'),
('die Sprache', 'language', 'n', 'work', 'Sprachen', 'Welche Sprachen sprichst du?', 'Which languages do you speak?'),
('sprechen', 'to speak', 'v', 'verb', '', 'Kann ich mit Herrn Klein sprechen?', 'Can I speak to Mr Klein?'),
('die Stadt', 'city / town', 'n', 'town', 'Städte', 'Heidelberg ist eine alte Stadt.', 'Heidelberg is an old city.'),
('stehen', 'to stand', 'v', 'verb', '', 'Der Bus steht schon an der Haltestelle.', 'The bus is already at the stop.'),
('stellen', 'to put (upright)', 'v', 'verb', '', 'Stell die Tasche rechts in die Ecke!', 'Put the bag in the right-hand corner!'),
('der Stock', 'floor / storey', 'n', 'home', 'Stockwerke', 'Unsere Wohnung liegt im ersten Stock.', 'Our apartment is on the first floor.'),
('die Straße', 'street', 'n', 'town', 'Straßen', 'In welcher Straße wohnen Sie?', 'Which street do you live on?'),
('die Straßenbahn', 'tram', 'n', 'trav', 'Straßenbahnen', 'Wo fährt die Straßenbahn ab?', 'Where does the tram leave from?'),
('studieren', 'to study (at university)', 'v', 'work', '', 'Ich studiere in Mainz.', 'I study in Mainz.'),
('das Studium', 'studies (university)', 'n', 'work', 'Studien', 'Das Studium beginnt im Oktober.', 'The degree programme starts in October.'),
('der Student', 'student (male)', 'n', 'work', 'Studenten', 'Mein Bruder ist Student.', 'My brother is a student.'),
('die Studentin', 'student (female)', 'n', 'work', 'Studentinnen', 'Ich bin Studentin.', 'I am a student.'),
('die Stunde', 'hour', 'n', 'time', 'Stunden', 'Ich bin in einer Stunde zurück.', 'I\'ll be back in an hour.'),
('suchen', 'to look for', 'v', 'verb', '', 'Suchst du etwas?', 'Are you looking for something?'),
('tanzen', 'to dance', 'v', 'free', '', 'Tanzen Sie gern?', 'Do you like dancing?'),
('die Tasche', 'bag / pocket', 'n', 'shop', 'Taschen', 'Ich habe die Schlüssel in der Tasche.', 'I have the keys in my bag.'),
('das Taxi', 'taxi', 'n', 'trav', 'Taxis', 'Es gibt heute keinen Bus mehr. Er fährt mit dem Taxi.', 'There are no more buses today. He is taking a taxi.'),
('der Tee', 'tea', 'n', 'food', 'Tees', 'Ich trinke morgens immer Tee.', 'I always drink tea in the morning.'),
('der Teil', 'part', 'n', 'work', 'Teile', 'Lies bitte auch den zweiten Teil.', 'Please read the second part as well.'),
('telefonieren', 'to phone', 'v', 'comm', '', 'Darf ich mal telefonieren?', 'May I make a phone call?'),
('das Telefon', 'telephone', 'n', 'comm', 'Telefone', 'Haben Sie Telefon?', 'Do you have a telephone?'),
('der Termin', 'appointment', 'n', 'work', 'Termine', 'Am besten machen wir sofort einen Termin.', 'It\'s best if we make an appointment right away.'),
('der Test', 'test', 'n', 'work', 'Tests', 'Der Test war einfach.', 'The test was easy.'),
('teuer', 'expensive', 'a', 'shop', '', 'Das ist mir zu teuer.', 'That is too expensive for me.'),
('der Text', 'text', 'n', 'work', 'Texte', 'Lesen Sie bitte diesen Text.', 'Please read this text.'),
('das Thema', 'topic', 'n', 'work', 'Themen', 'Wir sprechen heute über das Thema „Essen und Trinken“.', 'Today we are talking about the topic "Food and Drink".'),
('das Ticket', 'ticket', 'n', 'trav', 'Tickets', 'Wie viel kostet das Ticket?', 'How much is the ticket?'),
('der Tisch', 'table', 'n', 'home', 'Tische', 'Die Fotos liegen auf dem Tisch.', 'The photos are on the table.'),
('die Tochter', 'daughter', 'n', 'fam', 'Töchter', 'Das ist meine Tochter Katharina.', 'This is my daughter Katharina.'),
('die Toilette', 'toilet', 'n', 'home', 'Toiletten', 'Wo ist die Toilette, bitte?', 'Where is the toilet, please?'),
('die Tomate', 'tomato', 'n', 'food', 'Tomaten', 'Die Tomate ist noch grün.', 'The tomato is still green.'),
('tot', 'dead', 'a', 'per', '', 'Sein Vater ist schon lange tot.', 'His father died a long time ago.'),
('sich treffen', 'to meet', 'v', 'free', '', 'Wir treffen uns immer freitags.', 'We always meet on Fridays.'),
('die Treppe', 'stairs', 'n', 'home', 'Treppen', 'Die Toilette? Die Treppe hoch und dann links.', 'The toilet? Up the stairs and then left.'),
('trinken', 'to drink', 'v', 'food', '', 'Möchtest du etwas trinken?', 'Would you like something to drink?'),
('tschüss', 'bye', 'p', 'small', '', 'Junge Leute sagen meistens „tschüss“ und nicht „auf Wiedersehen“.', 'Young people usually say "bye" and not "goodbye".'),
('tun', 'to do', 'v', 'verb', '', 'Ich habe noch etwas zu tun.', 'I still have something to do.'),
('über', 'over / above / across', 'w', 'small', '', 'Gehen Sie hier über die Straße.', 'Cross the street here.'),
('übernachten', 'to stay the night', 'v', 'trav', '', 'Du kannst bei mir übernachten.', 'You can stay the night at my place.'),
('überweisen', 'to transfer (money)', 'v', 'shop', '', 'Sie können das Geld auch überweisen.', 'You can also transfer the money.'),
('die Uhr', 'clock / o\'clock', 'n', 'time', 'Uhren', 'Es ist vier Uhr.', 'It is four o\'clock.'),
('um', 'at (time) / around', 'w', 'small', '', 'Er kommt um sieben Uhr.', 'He is coming at seven o\'clock.'),
('umziehen', 'to move (house)', 'v', 'home', '', 'Nächsten Monat ziehen wir um.', 'We are moving next month.'),
('unser', 'our', 'w', 'small', '', 'Das ist unsere Lehrerin.', 'This is our teacher.'),
('unten', 'downstairs / below', 'd', 'small', '', 'Er wohnt ganz unten im Haus.', 'He lives at the very bottom of the building.'),
('unter', 'under / below', 'w', 'small', '', 'Unter uns wohnt eine Familie mit drei Kindern.', 'A family with three children lives below us.'),
('der Unterricht', 'lessons / class', 'n', 'work', '', 'Wir haben Unterricht von 8 bis 12 Uhr.', 'We have lessons from 8 to 12.'),
('unterschreiben', 'to sign', 'v', 'per', '', 'Wo muss ich unterschreiben?', 'Where do I have to sign?'),
('die Unterschrift', 'signature', 'n', 'per', 'Unterschriften', 'Hier fehlt noch Ihre Unterschrift.', 'Your signature is still missing here.'),
('der Urlaub', 'holiday / vacation', 'n', 'free', 'Urlaube', 'Ich nehme im September Urlaub.', 'I am taking holiday in September.'),
('der Vater', 'father', 'n', 'fam', 'Väter', 'Mein Vater ist Arbeiter.', 'My father is a worker.'),
('verboten', 'forbidden', 'a', 'desc', '', 'Hier ist Rauchen verboten.', 'Smoking is forbidden here.'),
('verdienen', 'to earn', 'v', 'work', '', 'Ich verdiene 1.500 Euro im Monat.', 'I earn 1,500 euros a month.'),
('der Verein', 'club / association', 'n', 'free', 'Vereine', 'Es gibt einen neuen Sportverein in der Stadt.', 'There is a new sports club in town.'),
('verheiratet', 'married', 'a', 'per', '', 'Ich bin verheiratet und habe drei Kinder.', 'I am married and have three children.'),
('verkaufen', 'to sell', 'v', 'shop', '', 'Er verkauft sein altes Auto.', 'He is selling his old car.'),
('der Verkäufer', 'shop assistant (male)', 'n', 'shop', 'Verkäufer', 'Der Verkäufer ist sehr freundlich.', 'The shop assistant is very friendly.'),
('die Verkäuferin', 'shop assistant (female)', 'n', 'shop', 'Verkäuferinnen', 'Meine Mutter ist Verkäuferin im Kaufhaus.', 'My mother is a shop assistant in a department store.'),
('vermieten', 'to rent out', 'v', 'home', '', 'Die Wohnung ist schon vermietet.', 'The apartment is already rented out.'),
('der Vermieter', 'landlord', 'n', 'home', 'Vermieter', 'Unser Vermieter heißt Huber. Er wohnt auch hier.', 'Our landlord is called Huber. He lives here too.'),
('verstehen', 'to understand', 'v', 'verb', '', 'Können Sie mich verstehen?', 'Can you understand me?'),
('der Verwandte', 'relative', 'n', 'fam', 'Verwandten', 'Peter besucht seine Verwandten in Polen.', 'Peter is visiting his relatives in Poland.'),
('viel', 'much / a lot', 'w', 'num', '', 'Hier regnet es viel.', 'It rains a lot here.'),
('vielleicht', 'maybe', 'd', 'small', '', 'Ich komme vielleicht mit dem Bus.', 'Maybe I\'ll come by bus.'),
('von', 'from / of', 'w', 'small', '', 'Das Auto von Felix ist kaputt.', 'Felix\'s car is broken.'),
('vor', 'before / in front of / ago', 'w', 'small', '', 'Das Auto steht vor der Tür.', 'The car is in front of the door.'),
('der Vorname', 'first name', 'n', 'per', 'Vornamen', 'Ich heiße Müller, mein Vorname ist Eva.', 'My surname is Müller, my first name is Eva.'),
('die Vorsicht', 'caution', 'n', 'small', '', 'Vorsicht! Da kommt ein Auto.', 'Careful! There\'s a car coming.'),
('sich vorstellen', 'to introduce oneself', 'v', 'per', '', 'Können Sie sich bitte vorstellen?', 'Could you introduce yourself, please?'),
('die Vorwahl', 'dialling code', 'n', 'comm', 'Vorwahlen', 'Wie ist die Vorwahl von München?', 'What is the dialling code for Munich?'),
('wandern', 'to hike', 'v', 'free', '', 'Wir wandern um den Chiemsee.', 'We are hiking around Lake Chiemsee.'),
('wann', 'when', 'w', 'small', '', 'Wann bist du fertig?', 'When will you be ready?'),
('warten', 'to wait', 'v', 'verb', '', 'Können Sie ein paar Minuten warten?', 'Can you wait a few minutes?'),
('warum', 'why', 'w', 'small', '', 'Warum kommt er nicht?', 'Why isn\'t he coming?'),
('was', 'what', 'w', 'small', '', 'Was ist das?', 'What is that?'),
('was für ein', 'what kind of', 'w', 'small', '', 'Was für eine Farbe möchten Sie?', 'What colour would you like?'),
('sich waschen', 'to wash (oneself)', 'v', 'home', '', 'Wo kann ich mir die Hände waschen?', 'Where can I wash my hands?'),
('das Wasser', 'water', 'n', 'food', '', 'Ein Glas Wasser, bitte.', 'A glass of water, please.'),
('wehtun', 'to hurt', 'v', 'body', '', 'Ich muss zum Arzt. Mein Bein tut weh.', 'I have to go to the doctor. My leg hurts.'),
('weiblich', 'female', 'a', 'per', '', 'Kreuzen Sie bitte an: „weiblich“ oder „männlich“.', 'Please tick: "female" or "male".'),
('der Wein', 'wine', 'n', 'food', 'Weine', 'Nein danke, ich möchte keinen Wein.', 'No thanks, I don\'t want any wine.'),
('weiter', 'further / on', 'd', 'trav', '', 'Der Bus fährt nicht weiter.', 'The bus does not go any further.'),
('welcher', 'which', 'w', 'small', '', 'Welches Buch möchtest du?', 'Which book would you like?'),
('die Welt', 'world', 'n', 'geo', 'Welten', 'Es gibt viele Probleme auf der Welt.', 'There are many problems in the world.'),
('wenig', 'little / few', 'w', 'num', '', 'Er verdient wenig.', 'He earns little.'),
('wer', 'who', 'w', 'small', '', 'Wer ist das?', 'Who is that?'),
('werden', 'to become', 'v', 'verb', '', 'Mein Sohn will Arzt werden.', 'My son wants to become a doctor.'),
('das Wetter', 'weather', 'n', 'nat', '', 'Wir hatten schlechtes Wetter.', 'We had bad weather.'),
('wichtig', 'important', 'a', 'desc', '', 'Dieses Formular ist sehr wichtig.', 'This form is very important.'),
('wie', 'how / like / as', 'w', 'small', '', 'Wie heißt du?', 'What is your name?'),
('wiederholen', 'to repeat', 'v', 'work', '', 'Können Sie das bitte wiederholen?', 'Can you repeat that, please?'),
('auf Wiederhören', 'goodbye (on the phone)', 'p', 'comm', '', 'Wir müssen jetzt Schluss machen. Also auf Wiederhören!', 'We have to finish now. Goodbye then!'),
('auf Wiedersehen', 'goodbye', 'p', 'small', '', 'Auf Wiedersehen, Frau Klein!', 'Goodbye, Ms Klein!'),
('wie viel', 'how much / how many', 'w', 'small', '', 'Wie viel Milch nehmen Sie?', 'How much milk do you take?'),
('willkommen', 'welcome', 'p', 'small', '', 'Herzlich willkommen!', 'Welcome!'),
('der Wind', 'wind', 'n', 'nat', 'Winde', 'Der Wind kommt aus Osten.', 'The wind is coming from the east.'),
('wir', 'we', 'w', 'small', '', 'Wir lernen Deutsch.', 'We are learning German.'),
('wissen', 'to know (a fact)', 'v', 'verb', '', 'Weißt du, wie er heißt?', 'Do you know what his name is?'),
('wo', 'where', 'w', 'small', '', 'Wo ist die Post?', 'Where is the post office?'),
('woher', 'where from', 'w', 'small', '', 'Woher kommen Sie?', 'Where are you from?'),
('wohin', 'where to', 'w', 'small', '', 'Wohin fährt dieser Bus?', 'Where does this bus go?'),
('wohnen', 'to live (reside)', 'v', 'home', '', 'Ich wohne in München.', 'I live in Munich.'),
('die Wohnung', 'apartment / flat', 'n', 'home', 'Wohnungen', 'Seit wann haben Sie diese Wohnung?', 'How long have you had this apartment?'),
('wollen', 'to want', 'v', 'verb', '', 'Wollen Sie einen Kaffee trinken?', 'Would you like to drink a coffee?'),
('das Wort', 'word', 'n', 'work', 'Wörter', 'Ich kenne das Wort nicht.', 'I don\'t know the word.'),
('wunderbar', 'wonderful', 'a', 'feel', '', 'Das Essen schmeckt wunderbar.', 'The food tastes wonderful.'),
('zahlen', 'to pay', 'v', 'shop', '', 'Zahlen, bitte!', 'The bill, please!'),
('die Zeit', 'time', 'n', 'time', 'Zeiten', 'Ich habe heute keine Zeit.', 'I don\'t have time today.'),
('zurzeit', 'at the moment', 'd', 'time', '', 'Zurzeit habe ich sehr viel zu tun.', 'At the moment I have a lot to do.'),
('die Zeitung', 'newspaper', 'n', 'free', 'Zeitungen', 'Ich lese gern Zeitung.', 'I like reading the newspaper.'),
('die Zigarette', 'cigarette', 'n', 'shop', 'Zigaretten', 'Wie teuer sind die Zigaretten?', 'How much are the cigarettes?'),
('das Zimmer', 'room', 'n', 'home', 'Zimmer', 'Die Wohnung hat drei Zimmer.', 'The apartment has three rooms.'),
('der Zoll', 'customs', 'n', 'trav', '', 'Wir müssen noch durch den Zoll.', 'We still have to go through customs.'),
('zu', 'to / too / closed', 'w', 'small', '', 'Der Bus fährt zum Bahnhof.', 'The bus goes to the station.'),
('zufrieden', 'satisfied', 'a', 'feel', '', 'Ich bin mit der Wohnung zufrieden.', 'I am happy with the apartment.'),
('der Zug', 'train', 'n', 'trav', 'Züge', 'Ich fahre gern mit dem Zug.', 'I like travelling by train.'),
('zurück', 'back', 'd', 'trav', '', 'Wann kommst du zurück?', 'When are you coming back?'),
('zusammen', 'together', 'd', 'small', '', 'Sollen wir zusammen essen gehen?', 'Shall we go out to eat together?'),
('zwischen', 'between', 'w', 'small', '', 'Heidelberg liegt zwischen Frankfurt und Stuttgart.', 'Heidelberg is between Frankfurt and Stuttgart.'),

# ---- word groups (numbers, colours, directions, measures, parts of the day) ----
('null', 'zero', 'w', 'num', '', 'Die Vorwahl beginnt mit null.', 'The dialling code starts with zero.'),
('eins', 'one', 'w', 'num', '', 'Es ist ein Uhr. Es ist eins.', 'It is one o\'clock.'),
('zwei', 'two', 'w', 'num', '', 'Ich habe zwei Kinder.', 'I have two children.'),
('drei', 'three', 'w', 'num', '', 'Drei Bananen, bitte!', 'Three bananas, please!'),
('vier', 'four', 'w', 'num', '', 'Es ist vier Uhr.', 'It is four o\'clock.'),
('fünf', 'five', 'w', 'num', '', 'Der Zug kommt in fünf Minuten.', 'The train comes in five minutes.'),
('sechs', 'six', 'w', 'num', '', 'Wir sind sechs Personen.', 'We are six people.'),
('sieben', 'seven', 'w', 'num', '', 'Die Woche hat sieben Tage.', 'The week has seven days.'),
('acht', 'eight', 'w', 'num', '', 'Ich schlafe acht Stunden.', 'I sleep eight hours.'),
('neun', 'nine', 'w', 'num', '', 'Der Kurs beginnt um neun Uhr.', 'The course starts at nine o\'clock.'),
('zehn', 'ten', 'w', 'num', '', 'Das kostet zehn Euro.', 'That costs ten euros.'),
('elf', 'eleven', 'w', 'num', '', 'Mein Sohn ist elf Jahre alt.', 'My son is eleven years old.'),
('zwölf', 'twelve', 'w', 'num', '', 'Ein Jahr hat zwölf Monate.', 'A year has twelve months.'),
('dreizehn', 'thirteen', 'w', 'num', '', 'Der Bus kommt um dreizehn Uhr.', 'The bus comes at 1 p.m.'),
('vierzehn', 'fourteen', 'w', 'num', '', 'Die Reise dauert vierzehn Tage.', 'The trip lasts fourteen days.'),
('fünfzehn', 'fifteen', 'w', 'num', '', 'Eine Viertelstunde sind fünfzehn Minuten.', 'A quarter of an hour is fifteen minutes.'),
('sechzehn', 'sixteen', 'w', 'num', '', 'Meine Tochter ist sechzehn.', 'My daughter is sixteen.'),
('siebzehn', 'seventeen', 'w', 'num', '', 'Das Zimmer hat die Nummer siebzehn.', 'The room is number seventeen.'),
('achtzehn', 'eighteen', 'w', 'num', '', 'Sind Sie über achtzehn?', 'Are you over eighteen?'),
('neunzehn', 'nineteen', 'w', 'num', '', 'Der Zug fährt von Gleis neunzehn.', 'The train leaves from platform nineteen.'),
('zwanzig', 'twenty', 'w', 'num', '', 'Ich habe noch zwanzig Euro.', 'I still have twenty euros.'),
('einundzwanzig', 'twenty-one', 'w', 'num', '', 'Claudia ist einundzwanzig.', 'Claudia is twenty-one.'),
('dreißig', 'thirty', 'w', 'num', '', 'Heute haben wir dreißig Grad.', 'It is thirty degrees today.'),
('vierzig', 'forty', 'w', 'num', '', 'Haben Sie das in Größe vierzig?', 'Do you have that in size forty?'),
('fünfzig', 'fifty', 'w', 'num', '', 'Es sind circa fünfzig Kilometer.', 'It is about fifty kilometres.'),
('sechzig', 'sixty', 'w', 'num', '', 'Eine Stunde hat sechzig Minuten.', 'An hour has sixty minutes.'),
('siebzig', 'seventy', 'w', 'num', '', 'Mein Opa ist siebzig.', 'My grandpa is seventy.'),
('achtzig', 'eighty', 'w', 'num', '', 'Mein Großvater ist schon achtzig.', 'My grandfather is already eighty.'),
('neunzig', 'ninety', 'w', 'num', '', 'Die Fahrt dauert neunzig Minuten.', 'The journey takes ninety minutes.'),
('hundert', 'hundred', 'w', 'num', '', 'Das Fahrrad kostet hundert Euro.', 'The bike costs a hundred euros.'),
('tausend', 'thousand', 'w', 'num', '', 'Die Miete ist tausend Euro.', 'The rent is a thousand euros.'),
('die Million', 'million', 'n', 'num', 'Millionen', 'Berlin hat fast vier Millionen Einwohner.', 'Berlin has almost four million inhabitants.'),
('erster', 'first', 'a', 'num', '', 'Heute ist der erste März.', 'Today is the first of March.'),
('zweiter', 'second', 'a', 'num', '', 'Im Zug fahre ich immer zweite Klasse.', 'I always travel second class on the train.'),
('dritter', 'third', 'a', 'num', '', 'Wir wohnen im dritten Stock.', 'We live on the third floor.'),
('halb', 'half', 'a', 'time', '', 'Es ist halb drei.', 'It is half past two.'),
('das Viertel', 'quarter', 'n', 'time', 'Viertel', 'Es ist Viertel nach zwei.', 'It is a quarter past two.'),
('der Euro', 'euro', 'n', 'num', 'Euro', 'Das kostet fünf Euro.', 'That costs five euros.'),
('der Cent', 'cent', 'n', 'num', 'Cent', 'Ein Euro hat hundert Cent.', 'A euro has a hundred cents.'),
('der Meter', 'metre', 'n', 'num', 'Meter', 'Die Wohnung ist nur hundert Meter vom Bahnhof entfernt.', 'The apartment is only a hundred metres from the station.'),
('der Kilometer', 'kilometre', 'n', 'num', 'Kilometer', 'Ich schwimme jeden Tag einen Kilometer.', 'I swim a kilometre every day.'),
('das Kilo', 'kilo', 'n', 'num', 'Kilo', 'Ein Kilo Birnen, bitte!', 'A kilo of pears, please!'),
('das Pfund', 'pound (500 g)', 'n', 'num', 'Pfund', 'Ein Pfund Äpfel, bitte.', 'A pound of apples, please.'),
('der Liter', 'litre', 'n', 'num', 'Liter', 'Ich trinke zwei Liter Wasser am Tag.', 'I drink two litres of water a day.'),
('das Gramm', 'gram', 'n', 'num', 'Gramm', 'Ich möchte 200 Gramm Schinken.', 'I would like 200 grams of ham.'),
('das Prozent', 'percent', 'n', 'num', 'Prozent', 'Heute gibt es zwanzig Prozent auf alle Schuhe.', 'Today there is twenty percent off all shoes.'),
('grau', 'grey', 'a', 'col', '', 'Der Himmel ist grau.', 'The sky is grey.'),
('braun', 'brown', 'a', 'col', '', 'Sie hat braune Augen.', 'She has brown eyes.'),
('der Norden', 'north', 'n', 'geo', '', 'Hamburg liegt im Norden.', 'Hamburg is in the north.'),
('der Süden', 'south', 'n', 'geo', '', 'München liegt im Süden.', 'Munich is in the south.'),
('der Westen', 'west', 'n', 'geo', '', 'Köln liegt im Westen.', 'Cologne is in the west.'),
('der Osten', 'east', 'n', 'geo', '', 'Der Wind kommt aus Osten.', 'The wind is coming from the east.'),
('Deutschland', 'Germany', 'w', 'geo', '', 'Ich wohne seit zwei Jahren in Deutschland.', 'I have lived in Germany for two years.'),
('deutsch', 'German (adjective)', 'a', 'geo', '', 'Wie heißt das auf Deutsch?', 'What is that called in German?'),
('der Deutsche', 'German (person)', 'n', 'geo', 'Deutschen', 'Mein Mann ist Deutscher.', 'My husband is German.'),
('Europa', 'Europe', 'w', 'geo', '', 'Deutschland liegt in Europa.', 'Germany is in Europe.'),
('der Morgen', 'morning', 'n', 'time', 'Morgen', 'Guten Morgen!', 'Good morning!'),
('der Vormittag', 'late morning', 'n', 'time', 'Vormittage', 'Am Vormittag bin ich im Büro.', 'In the morning I am at the office.'),
('der Wochentag', 'weekday', 'n', 'time', 'Wochentage', 'Welcher Wochentag ist heute?', 'What day of the week is it today?'),
('der Sonnabend', 'Saturday (north German)', 'n', 'time', 'Sonnabende', 'Am Sonnabend gehe ich einkaufen.', 'On Saturday I go shopping.'),
('das Frühjahr', 'spring', 'n', 'time', 'Frühjahre', 'Im Frühjahr blühen die Bäume.', 'In spring the trees blossom.'),
]
