# Goethe-Zertifikat A1 (Start Deutsch 1) word list, A–E.
# (German, English, type, category, plural, example, example in English)
# type: n noun, v verb, a adjective, d adverb, w small word, p phrase
ROWS = [
('ab', 'from (a time)', 'w', 'small', '', 'Ab morgen muss ich arbeiten.', 'From tomorrow I have to work.'),
('aber', 'but', 'w', 'small', '', 'Ich bin oft im Büro, aber nur für wenige Stunden.', 'I am often in the office, but only for a few hours.'),
('abfahren', 'to depart', 'v', 'trav', '', 'Wir fahren um zwölf Uhr ab.', 'We leave at twelve o\'clock.'),
('die Abfahrt', 'departure', 'n', 'trav', 'Abfahrten', 'Vor der Abfahrt rufe ich an.', 'I will call before the departure.'),
('abgeben', 'to hand in', 'v', 'verb', '', 'Ich muss meine Schlüssel abgeben.', 'I have to hand in my keys.'),
('abholen', 'to pick up', 'v', 'verb', '', 'Wir müssen noch meinen Bruder abholen.', 'We still have to pick up my brother.'),
('der Absender', 'sender', 'n', 'comm', 'Absender', 'Da ist ein Brief für dich ohne Absender.', 'There is a letter for you without a sender.'),
('Achtung', 'attention! / watch out!', 'p', 'small', '', 'Achtung! Das dürfen Sie nicht tun.', 'Attention! You are not allowed to do that.'),
('die Adresse', 'address', 'n', 'per', 'Adressen', 'Können Sie mir seine Adresse sagen?', 'Can you tell me his address?'),
('alle', 'all / everyone', 'w', 'small', '', 'Sind alle da?', 'Is everyone here?'),
('allein', 'alone', 'd', 'desc', '', 'Er kommt allein.', 'He is coming alone.'),
('also', 'so / therefore', 'w', 'small', '', 'Er hat Zeit, also muss er uns helfen.', 'He has time, so he has to help us.'),
('alt', 'old', 'a', 'desc', '', 'Wie alt sind Sie?', 'How old are you?'),
('das Alter', 'age', 'n', 'per', '', 'Alter: 26 Jahre.', 'Age: 26 years.'),
('an', 'at / on', 'w', 'small', '', 'Wir treffen uns am Bahnhof.', 'We meet at the station.'),
('anbieten', 'to offer', 'v', 'verb', '', 'Was darf ich dir anbieten?', 'What can I offer you?'),
('das Angebot', 'offer / special offer', 'n', 'shop', 'Angebote', 'Heute sind Sportschuhe im Angebot.', 'Sports shoes are on offer today.'),
('andere', 'other', 'a', 'small', '', 'Willst du diese Jacke? – Nein, ich möchte die andere.', 'Do you want this jacket? – No, I would like the other one.'),
('anfangen', 'to begin', 'v', 'verb', '', 'Der Unterricht fängt gleich an.', 'The lesson is starting right away.'),
('der Anfang', 'beginning', 'n', 'time', 'Anfänge', 'Wir machen Anfang Juli Urlaub.', 'We are going on holiday at the beginning of July.'),
('anklicken', 'to click on', 'v', 'comm', '', 'Da musst du dieses Wort anklicken.', 'You have to click on this word there.'),
('ankommen', 'to arrive', 'v', 'trav', '', 'Wann kommt dieser Zug in Hamburg an?', 'When does this train arrive in Hamburg?'),
('die Ankunft', 'arrival', 'n', 'trav', 'Ankünfte', 'Auf diesem Plan steht nur die Ankunft der Züge.', 'This timetable only shows the arrival of the trains.'),
('ankreuzen', 'to tick / to mark with a cross', 'v', 'per', '', 'Auf dem Formular müssen Sie an mehreren Stellen etwas ankreuzen.', 'You have to tick several places on the form.'),
('anmachen', 'to switch on', 'v', 'home', '', 'Mach bitte das Licht an!', 'Please switch on the light!'),
('sich anmelden', 'to register', 'v', 'per', '', 'Wo kann ich mich anmelden?', 'Where can I register?'),
('die Anmeldung', 'registration / reception', 'n', 'per', 'Anmeldungen', 'Eine Anmeldung für diesen Kurs ist nicht mehr möglich.', 'Registration for this course is no longer possible.'),
('die Anrede', 'form of address / greeting', 'n', 'comm', 'Anreden', 'Schreiben Sie auch eine Anrede und einen Gruß.', 'Also write a greeting and a closing.'),
('anrufen', 'to call (phone)', 'v', 'comm', '', 'Peter ruft kurz seine Freundin an.', 'Peter quickly calls his girlfriend.'),
('der Anruf', 'phone call', 'n', 'comm', 'Anrufe', 'Sie bekommt viele Anrufe auf ihrem Handy.', 'She gets many calls on her mobile.'),
('der Anrufbeantworter', 'answering machine', 'n', 'comm', 'Anrufbeantworter', 'Wir sind im Moment nicht da. Sprechen Sie bitte auf den Anrufbeantworter.', 'We are not here at the moment. Please leave a message on the answering machine.'),
('die Ansage', 'announcement', 'n', 'comm', 'Ansagen', 'Hören Sie die Ansagen.', 'Listen to the announcements.'),
('der Anschluss', 'connection', 'n', 'trav', 'Anschlüsse', 'In Mannheim haben Sie Anschluss nach Saarbrücken.', 'In Mannheim you have a connection to Saarbrücken.'),
('an sein', 'to be on (switched on)', 'v', 'home', '', 'Heute Nacht war das Licht an.', 'The light was on last night.'),
('antworten', 'to answer', 'v', 'verb', '', 'Er antwortet nicht.', 'He does not answer.'),
('die Antwort', 'answer', 'n', 'work', 'Antworten', 'Er gibt leider keine Antwort.', 'Unfortunately he gives no answer.'),
('die Anzeige', 'advertisement', 'n', 'comm', 'Anzeigen', 'Ich habe Ihre Anzeige in der Zeitung gelesen.', 'I read your advertisement in the newspaper.'),
('sich anziehen', 'to get dressed / to put on', 'v', 'verb', '', 'Ich muss mich noch anziehen.', 'I still have to get dressed.'),
('das Apartment', 'apartment / studio flat', 'n', 'home', 'Apartments', 'Wir haben ein Apartment gemietet.', 'We have rented an apartment.'),
('der Apfel', 'apple', 'n', 'food', 'Äpfel', 'Ein Pfund Äpfel bitte.', 'A pound of apples, please.'),
('der Appetit', 'appetite', 'n', 'food', '', 'Guten Appetit!', 'Enjoy your meal!'),
('arbeiten', 'to work', 'v', 'work', '', 'Wo arbeiten Sie?', 'Where do you work?'),
('die Arbeit', 'work', 'n', 'work', 'Arbeiten', 'Mein Bruder sucht Arbeit.', 'My brother is looking for work.'),
('arbeitslos', 'unemployed', 'a', 'work', '', 'Es gibt bei uns viele Leute, die schon lange arbeitslos sind.', 'Where we live, many people have been unemployed for a long time.'),
('der Arbeitsplatz', 'workplace / job', 'n', 'work', 'Arbeitsplätze', 'An meinem Arbeitsplatz fehlt ein Drucker.', 'There is no printer at my workplace.'),
('der Arm', 'arm', 'n', 'body', 'Arme', 'Mein Arm tut weh.', 'My arm hurts.'),
('der Arzt', 'doctor (male)', 'n', 'body', 'Ärzte', 'Morgen habe ich einen Termin beim Arzt.', 'Tomorrow I have an appointment at the doctor\'s.'),
('die Ärztin', 'doctor (female)', 'n', 'body', 'Ärztinnen', 'Morgen habe ich einen Termin bei meiner Ärztin.', 'Tomorrow I have an appointment with my doctor.'),
('auch', 'also / too', 'w', 'small', '', 'Ich bin auch Spanier.', 'I am Spanish too.'),
('auf', 'on / onto', 'w', 'small', '', 'Die Kinder spielen auf der Straße.', 'The children are playing on the street.'),
('die Aufgabe', 'task / exercise', 'n', 'work', 'Aufgaben', 'Das ist eine schwere Aufgabe.', 'That is a difficult task.'),
('aufhören', 'to stop / to end', 'v', 'verb', '', 'Der Kurs hört in einer Woche auf.', 'The course ends in one week.'),
('auf sein', 'to be open', 'v', 'home', '', 'Du brauchst den Schlüssel nicht. Die Wohnung ist auf.', 'You don\'t need the key. The apartment is open.'),
('aufstehen', 'to get up', 'v', 'verb', '', 'Ich muss immer um vier Uhr aufstehen.', 'I always have to get up at four o\'clock.'),
('der Aufzug', 'lift / elevator', 'n', 'home', 'Aufzüge', 'In diesem Haus gibt es keinen Aufzug.', 'There is no lift in this building.'),
('das Auge', 'eye', 'n', 'body', 'Augen', 'Er hat blaue Augen.', 'He has blue eyes.'),
('aus', 'from / out of', 'w', 'small', '', 'Er kommt aus Brasilien.', 'He comes from Brazil.'),
('der Ausflug', 'trip / excursion', 'n', 'free', 'Ausflüge', 'Morgen machen wir einen Ausflug nach Heidelberg.', 'Tomorrow we are going on a trip to Heidelberg.'),
('ausfüllen', 'to fill in', 'v', 'per', '', 'Füllen Sie bitte dieses Formular aus.', 'Please fill in this form.'),
('der Ausgang', 'exit', 'n', 'town', 'Ausgänge', 'Wo ist der Ausgang?', 'Where is the exit?'),
('die Auskunft', 'information', 'n', 'trav', 'Auskünfte', 'Können Sie mir eine Auskunft geben?', 'Can you give me some information?'),
('das Ausland', 'abroad / foreign countries', 'n', 'geo', '', 'Fahren Sie ins Ausland?', 'Are you going abroad?'),
('der Ausländer', 'foreigner (male)', 'n', 'geo', 'Ausländer', 'Sind Sie Ausländer?', 'Are you a foreigner?'),
('die Ausländerin', 'foreigner (female)', 'n', 'geo', 'Ausländerinnen', 'Sind Sie Ausländerin?', 'Are you a foreigner?'),
('ausländisch', 'foreign', 'a', 'geo', '', 'Leider habe ich nur ausländisches Geld.', 'Unfortunately I only have foreign money.'),
('ausmachen', 'to switch off', 'v', 'home', '', 'Mach bitte das Licht aus!', 'Please switch off the light!'),
('die Aussage', 'statement', 'n', 'work', 'Aussagen', 'Ist die Aussage richtig oder falsch?', 'Is the statement true or false?'),
('aussehen', 'to look (appear)', 'v', 'verb', '', 'Das sieht schön aus.', 'That looks nice.'),
('aus sein', 'to be off / to be over', 'v', 'home', '', 'Das Licht ist aus.', 'The light is off.'),
('aussteigen', 'to get off (a vehicle)', 'v', 'trav', '', 'Wo muss ich aussteigen?', 'Where do I have to get off?'),
('der Ausweis', 'ID card', 'n', 'per', 'Ausweise', 'Hier ist mein Ausweis.', 'Here is my ID card.'),
('sich ausziehen', 'to get undressed / to take off', 'v', 'verb', '', 'Zieh die Schuhe aus, bitte!', 'Take your shoes off, please!'),
('das Auto', 'car', 'n', 'trav', 'Autos', 'Er kommt mit dem Auto.', 'He is coming by car.'),
('die Autobahn', 'motorway', 'n', 'trav', 'Autobahnen', 'Wo geht es hier bitte zur Autobahn?', 'Which way to the motorway, please?'),
('der Automat', 'machine (vending/ticket)', 'n', 'trav', 'Automaten', 'Die Fahrkarten gibt es nur am Automaten.', 'Tickets are only available from the machine.'),
('automatisch', 'automatic', 'a', 'desc', '', 'Du musst nichts machen. Das geht automatisch.', 'You don\'t have to do anything. It works automatically.'),
('das Baby', 'baby', 'n', 'fam', 'Babys', 'Mein Kind ist noch ein Baby.', 'My child is still a baby.'),
('die Bäckerei', 'bakery', 'n', 'shop', 'Bäckereien', 'Ich gehe mal schnell zur Bäckerei.', 'I\'m just popping to the bakery.'),
('das Bad', 'bathroom / bath', 'n', 'home', 'Bäder', 'Wir haben kein großes Bad.', 'We don\'t have a big bathroom.'),
('baden', 'to take a bath', 'v', 'home', '', 'Ich bade nicht so gern, ich dusche lieber.', 'I don\'t like baths much, I prefer to shower.'),
('die Bahn', 'train / railway', 'n', 'trav', 'Bahnen', 'Wir fahren lieber mit der Bahn.', 'We prefer to go by train.'),
('der Bahnhof', 'train station', 'n', 'trav', 'Bahnhöfe', 'Komme ich hier zum Bahnhof?', 'Is this the way to the station?'),
('der Bahnsteig', 'platform', 'n', 'trav', 'Bahnsteige', 'Auf welchem Bahnsteig fährt der Zug?', 'Which platform does the train leave from?'),
('bald', 'soon', 'd', 'time', '', 'Ich komme bald.', 'I am coming soon.'),
('der Balkon', 'balcony', 'n', 'home', 'Balkone', 'Die Wohnung hat auch einen kleinen Balkon.', 'The apartment also has a small balcony.'),
('die Banane', 'banana', 'n', 'food', 'Bananen', 'Drei Bananen, bitte!', 'Three bananas, please!'),
('die Bank', 'bank / bench', 'n', 'town', 'Banken', 'Er sitzt im Park auf einer Bank und liest.', 'He is sitting on a bench in the park, reading. (Plural: Banken for banks, Bänke for benches.)'),
('bar', 'in cash', 'd', 'shop', '', 'Muss ich bar zahlen oder geht es auch mit Karte?', 'Do I have to pay cash or can I pay by card?'),
('der Bauch', 'belly / stomach', 'n', 'body', 'Bäuche', 'Seit gestern tut mir der Bauch weh.', 'My stomach has hurt since yesterday.'),
('der Baum', 'tree', 'n', 'nat', 'Bäume', 'Vorsicht, fahr nicht an den Baum!', 'Careful, don\'t drive into the tree!'),
('der Beamte', 'civil servant / official', 'n', 'work', 'Beamten', 'Der Beamte arbeitet bei der Stadt.', 'The official works for the city.'),
('die Beamtin', 'civil servant (female)', 'n', 'work', 'Beamtinnen', 'Fragen Sie die Beamtin an Schalter acht!', 'Ask the official at counter eight!'),
('bedeuten', 'to mean', 'v', 'verb', '', 'Was bedeutet das Wort?', 'What does the word mean?'),
('beginnen', 'to begin', 'v', 'verb', '', 'Das Spiel beginnt um 15.30 Uhr.', 'The game starts at 3.30 p.m.'),
('bei', 'at / near / with', 'w', 'small', '', 'Ich wohne bei meinen Eltern.', 'I live with my parents.'),
('beide', 'both', 'w', 'small', '', 'Beide Eltern arbeiten.', 'Both parents work.'),
('das Bein', 'leg', 'n', 'body', 'Beine', 'Mein rechtes Bein tut weh.', 'My right leg hurts.'),
('das Beispiel', 'example', 'n', 'work', 'Beispiele', 'Kannst du mir ein Beispiel sagen?', 'Can you give me an example?'),
('zum Beispiel', 'for example (z. B.)', 'p', 'small', '', 'Viele meiner Verwandten, zum Beispiel meine beiden Brüder, arbeiten auch hier.', 'Many of my relatives, for example my two brothers, also work here.'),
('bekannt', 'well-known / famous', 'a', 'desc', '', 'Picasso ist sehr bekannt.', 'Picasso is very famous.'),
('der Bekannte', 'acquaintance', 'n', 'fam', 'Bekannten', 'Ein Bekannter von mir heißt Klaus.', 'An acquaintance of mine is called Klaus.'),
('bekommen', 'to get / to receive', 'v', 'verb', '', 'Haben Sie meinen Brief bekommen?', 'Did you receive my letter?'),
('benutzen', 'to use', 'v', 'verb', '', 'Die Aufzüge bitte nicht benutzen!', 'Please do not use the lifts!'),
('der Beruf', 'job / profession', 'n', 'work', 'Berufe', 'Was sind Sie von Beruf?', 'What do you do for a living?'),
('besetzt', 'occupied / busy (phone)', 'a', 'desc', '', 'Die Nummer ist immer besetzt.', 'The number is always busy.'),
('besichtigen', 'to visit / to see (sights)', 'v', 'free', '', 'Ich möchte gern den Dom besichtigen.', 'I would like to see the cathedral.'),
('besser', 'better', 'a', 'desc', '', 'Es geht mir schon besser.', 'I am already feeling better.'),
('am besten', 'best', 'd', 'desc', '', 'Am besten treffen wir uns morgen.', 'It\'s best if we meet tomorrow.'),
('bestellen', 'to order', 'v', 'food', '', 'Wir möchten bestellen, bitte.', 'We would like to order, please.'),
('besuchen', 'to visit', 'v', 'verb', '', 'Darf ich dich besuchen?', 'May I visit you?'),
('das Bett', 'bed', 'n', 'home', 'Betten', 'Wir brauchen noch ein Kinderbett.', 'We still need a child\'s bed.'),
('bezahlen', 'to pay', 'v', 'shop', '', 'Wo muss ich bezahlen?', 'Where do I have to pay?'),
('das Bier', 'beer', 'n', 'food', 'Biere', 'Noch ein Bier bitte.', 'Another beer, please.'),
('das Bild', 'picture', 'n', 'home', 'Bilder', 'Hast du ein Bild von deinem Sohn?', 'Do you have a picture of your son?'),
('die Birne', 'pear', 'n', 'food', 'Birnen', 'Ein Kilo Birnen, bitte!', 'A kilo of pears, please!'),
('bis', 'until / as far as', 'w', 'small', '', 'Ich warte bis morgen.', 'I\'ll wait until tomorrow.'),
('ein bisschen', 'a little', 'w', 'small', '', 'Ich spreche Englisch, Französisch und ein bisschen Deutsch.', 'I speak English, French and a little German.'),
('bitte', 'please / you\'re welcome', 'p', 'small', '', 'Eine Tasse Kaffee, bitte!', 'A cup of coffee, please!'),
('die Bitte', 'request', 'n', 'small', 'Bitten', 'Ich habe noch eine Bitte.', 'I have one more request.'),
('bitten', 'to ask (for)', 'v', 'verb', '', 'Darf ich Sie um etwas bitten?', 'May I ask you for something?'),
('bitter', 'bitter', 'a', 'food', '', 'Der Kaffee schmeckt bitter.', 'The coffee tastes bitter.'),
('bleiben', 'to stay', 'v', 'verb', '', 'Ich bleibe heute zu Hause.', 'I\'m staying at home today.'),
('der Bleistift', 'pencil', 'n', 'work', 'Bleistifte', 'Hast du einen Bleistift?', 'Do you have a pencil?'),
('der Blick', 'view / look', 'n', 'free', 'Blicke', 'Von diesem Hotel hat man einen guten Blick auf den Rhein.', 'From this hotel you have a good view of the Rhine.'),
('die Blume', 'flower', 'n', 'nat', 'Blumen', 'Gefallen dir die Blumen?', 'Do you like the flowers?'),
('der Bogen', 'sheet (of paper)', 'n', 'work', 'Bögen', 'Schreiben Sie Ihre Lösungen bitte auf den Antwortbogen.', 'Please write your answers on the answer sheet.'),
('böse', 'angry / bad', 'a', 'feel', '', 'Sie ist böse auf mich.', 'She is angry with me.'),
('brauchen', 'to need', 'v', 'verb', '', 'Brauchst du die Zeitung noch?', 'Do you still need the newspaper?'),
('breit', 'wide', 'a', 'desc', '', 'Wie breit ist der Schrank?', 'How wide is the wardrobe?'),
('der Brief', 'letter', 'n', 'comm', 'Briefe', 'Haben Sie einen Brief für mich?', 'Do you have a letter for me?'),
('die Briefmarke', 'stamp', 'n', 'comm', 'Briefmarken', 'Kaufst du bitte Briefmarken bei der Post?', 'Could you buy stamps at the post office, please?'),
('bringen', 'to bring', 'v', 'verb', '', 'Bringen Sie mir bitte noch einen Kaffee!', 'Please bring me another coffee!'),
('das Brot', 'bread', 'n', 'food', 'Brote', 'Nimm noch ein paar Brote für die Fahrt mit.', 'Take a few sandwiches for the journey.'),
('das Brötchen', 'bread roll', 'n', 'food', 'Brötchen', 'Möchtest du Brötchen zum Frühstück?', 'Would you like rolls for breakfast?'),
('der Bruder', 'brother', 'n', 'fam', 'Brüder', 'Sein Bruder arbeitet auch hier.', 'His brother also works here.'),
('das Buch', 'book', 'n', 'free', 'Bücher', 'Gute Bücher sind oft sehr teuer.', 'Good books are often very expensive.'),
('der Buchstabe', 'letter (of the alphabet)', 'n', 'work', 'Buchstaben', 'Diesen Buchstaben gibt es in meiner Sprache nicht.', 'This letter does not exist in my language.'),
('buchstabieren', 'to spell', 'v', 'per', '', 'Bitte buchstabieren Sie Ihren Namen.', 'Please spell your name.'),
('der Bus', 'bus', 'n', 'trav', 'Busse', 'Wann kommt der nächste Bus?', 'When does the next bus come?'),
('die Butter', 'butter', 'n', 'food', '', 'Für mich bitte ein Brötchen mit Butter und Käse.', 'A roll with butter and cheese for me, please.'),
('das Café', 'café', 'n', 'town', 'Cafés', 'Sollen wir uns im Café treffen?', 'Shall we meet at the café?'),
('die CD', 'CD', 'n', 'free', 'CDs', 'Bring bitte deine Lieblings-CD mit.', 'Please bring your favourite CD.'),
('der Chef', 'boss (male)', 'n', 'work', 'Chefs', 'Der Chef ist heute nicht da.', 'The boss is not here today.'),
('die Chefin', 'boss (female)', 'n', 'work', 'Chefinnen', 'Wir haben eine neue Chefin.', 'We have a new boss.'),
('circa', 'about / approximately (ca.)', 'w', 'num', '', 'Von Mainz nach Frankfurt sind es circa fünfzig Kilometer.', 'From Mainz to Frankfurt it is about fifty kilometres.'),
('der Computer', 'computer', 'n', 'comm', 'Computer', 'Wann bekommst du deinen neuen Computer?', 'When are you getting your new computer?'),
('da', 'there / here', 'w', 'small', '', 'Ist Herr Klein schon da?', 'Is Mr Klein here yet?'),
('die Dame', 'lady', 'n', 'per', 'Damen', 'Meine Damen und Herren!', 'Ladies and gentlemen!'),
('daneben', 'next to it', 'w', 'small', '', 'Du kennst doch die Post. Daneben ist die Bank.', 'You know the post office. The bank is next to it.'),
('danken', 'to thank', 'v', 'verb', '', 'Ich danke Ihnen für die Einladung.', 'Thank you for the invitation.'),
('der Dank', 'thanks', 'n', 'small', '', 'Vielen Dank!', 'Many thanks!'),
('danke', 'thank you', 'p', 'small', '', 'Soll ich Ihnen helfen? – Nein, danke!', 'Shall I help you? – No, thank you!'),
('dann', 'then', 'd', 'time', '', 'Ich muss noch schnell zur Post, dann komme ich.', 'I just have to go to the post office, then I\'ll come.'),
('das Datum', 'date', 'n', 'per', 'Daten', 'Bitte schreiben Sie noch das Datum auf das Formular.', 'Please also write the date on the form.'),
('dauern', 'to last / to take (time)', 'v', 'verb', '', 'Wie lange dauert der Film?', 'How long is the film?'),
('dein', 'your (informal)', 'w', 'small', '', 'Ist das dein Auto?', 'Is that your car?'),
('denn', 'because / then (in questions)', 'w', 'small', '', 'Ich kann nicht kommen, denn ich bin krank.', 'I can\'t come because I am sick.'),
('dich', 'you (accusative)', 'w', 'small', '', 'Die Blumen sind für dich.', 'The flowers are for you.'),
('dieser', 'this', 'w', 'small', '', 'Ich nehme lieber diesen Kuchen.', 'I\'d rather have this cake.'),
('dir', 'to you (dative)', 'w', 'small', '', 'Gefallen dir die Blumen?', 'Do you like the flowers?'),
('die Disco', 'disco / club', 'n', 'free', 'Discos', 'Heute Abend gehen wir in die Disco tanzen.', 'Tonight we are going dancing at the club.'),
('der Doktor', 'doctor', 'n', 'body', 'Doktoren', 'Meine Tochter ist krank. Wir gehen zum Doktor.', 'My daughter is sick. We are going to the doctor.'),
('das Doppelzimmer', 'double room', 'n', 'trav', 'Doppelzimmer', 'Wollen Sie ein Doppelzimmer oder ein Einzelzimmer?', 'Do you want a double room or a single room?'),
('das Dorf', 'village', 'n', 'town', 'Dörfer', 'Meine Familie lebt in einem Dorf.', 'My family lives in a village.'),
('dort', 'there', 'w', 'small', '', 'Dort ist unser Haus.', 'Our house is over there.'),
('draußen', 'outside', 'd', 'small', '', 'Wollen wir draußen sitzen?', 'Shall we sit outside?'),
('drucken', 'to print', 'v', 'comm', '', 'Bitte drucke das Formular für mich.', 'Please print the form for me.'),
('der Drucker', 'printer', 'n', 'comm', 'Drucker', 'Mein Drucker ist kaputt.', 'My printer is broken.'),
('drücken', 'to press / to push', 'v', 'verb', '', 'Drück hier, dann geht der Computer an.', 'Press here, then the computer switches on.'),
('durch', 'through', 'w', 'small', '', 'Am besten gehen Sie durch die Breite Straße.', 'It\'s best to go through Breite Straße.'),
('die Durchsage', 'announcement (loudspeaker)', 'n', 'trav', 'Durchsagen', 'Ich habe die Durchsage nicht verstanden.', 'I didn\'t understand the announcement.'),
('dürfen', 'may / to be allowed to', 'v', 'verb', '', 'Sie dürfen hier nicht rauchen.', 'You are not allowed to smoke here.'),
('der Durst', 'thirst', 'n', 'food', '', 'Hast du etwas zu trinken? Ich habe großen Durst.', 'Do you have something to drink? I am very thirsty.'),
('duschen', 'to shower', 'v', 'home', '', 'Ich bade nicht so gern, ich dusche lieber.', 'I don\'t like baths much, I prefer to shower.'),
('die Dusche', 'shower', 'n', 'home', 'Duschen', 'Unsere Wohnung hat nur eine Dusche.', 'Our apartment only has a shower.'),
('die Ecke', 'corner', 'n', 'town', 'Ecken', 'An der nächsten Ecke links.', 'Left at the next corner.'),
('die Ehefrau', 'wife', 'n', 'fam', 'Ehefrauen', 'Das ist meine Ehefrau.', 'This is my wife.'),
('der Ehemann', 'husband', 'n', 'fam', 'Ehemänner', 'Das ist mein Ehemann.', 'This is my husband.'),
('das Ei', 'egg', 'n', 'food', 'Eier', 'Möchtest du ein Ei zum Frühstück?', 'Would you like an egg for breakfast?'),
('eilig', 'urgent / in a hurry', 'a', 'feel', '', 'Hast du es eilig?', 'Are you in a hurry?'),
('ein', 'a / an / one', 'w', 'small', '', 'Ich nehme ein Bier. Willst du auch eins?', 'I\'ll have a beer. Do you want one too?'),
('einfach', 'simple / single (ticket)', 'a', 'desc', '', 'Hin und zurück? – Nein, bitte nur einfach.', 'Return? – No, just a single, please.'),
('der Eingang', 'entrance', 'n', 'town', 'Eingänge', 'Der Eingang ist um die Ecke.', 'The entrance is around the corner.'),
('einkaufen', 'to go shopping', 'v', 'shop', '', 'Ich muss noch für morgen einkaufen.', 'I still have to go shopping for tomorrow.'),
('einladen', 'to invite', 'v', 'free', '', 'Darf ich Sie zu einem Kaffee einladen?', 'May I invite you for a coffee?'),
('die Einladung', 'invitation', 'n', 'free', 'Einladungen', 'Danke für die Einladung!', 'Thanks for the invitation!'),
('einmal', 'once', 'd', 'time', '', 'Diese Prüfung mache ich nicht noch einmal.', 'I won\'t take this exam again.'),
('einsteigen', 'to get on (a vehicle)', 'v', 'trav', '', 'Schnell, steig ein, der Zug fährt gleich.', 'Quick, get on, the train is about to leave.'),
('der Eintritt', 'admission / entry fee', 'n', 'free', 'Eintritte', 'Der Preis für den Eintritt ist 5 Euro.', 'The admission price is 5 euros.'),
('das Einzelzimmer', 'single room', 'n', 'trav', 'Einzelzimmer', 'Haben Sie noch ein Einzelzimmer?', 'Do you still have a single room?'),
('die Eltern', 'parents (plural)', 'n', 'fam', '', 'Meine Eltern leben in Spanien.', 'My parents live in Spain.'),
('die E-Mail', 'email', 'n', 'comm', 'E-Mails', 'Ich habe Ihre E-Mail nicht bekommen.', 'I did not get your email.'),
('der Empfänger', 'recipient', 'n', 'comm', 'Empfänger', 'Auf dem Brief steht dein Name, also bist du der Empfänger.', 'Your name is on the letter, so you are the recipient.'),
('empfehlen', 'to recommend', 'v', 'verb', '', 'Welchen Wein können Sie mir empfehlen?', 'Which wine can you recommend?'),
('enden', 'to end', 'v', 'verb', '', 'Die Straße endet hier.', 'The street ends here.'),
('das Ende', 'end', 'n', 'time', 'Enden', 'Er bekommt sein Geld am Ende des Monats.', 'He gets his money at the end of the month.'),
('entschuldigen', 'to excuse', 'v', 'verb', '', 'Entschuldigen Sie bitte!', 'Excuse me, please!'),
('die Entschuldigung', 'apology / excuse me', 'n', 'small', 'Entschuldigungen', 'Entschuldigung! – Bitte.', 'Sorry! – That\'s all right.'),
('er', 'he', 'w', 'small', '', 'Er heißt Ali.', 'His name is Ali.'),
('das Ergebnis', 'result', 'n', 'work', 'Ergebnisse', 'Das Ergebnis des Tests bekommen Sie in zwei Wochen.', 'You will get the test result in two weeks.'),
('erklären', 'to explain', 'v', 'verb', '', 'Kannst du mir das erklären?', 'Can you explain that to me?'),
('erlauben', 'to allow', 'v', 'verb', '', 'Rauchen ist hier nicht erlaubt.', 'Smoking is not allowed here.'),
('der Erwachsene', 'adult', 'n', 'fam', 'Erwachsenen', 'Dieser Film ist nur für Erwachsene.', 'This film is for adults only.'),
('erzählen', 'to tell', 'v', 'verb', '', 'Wir müssen euch etwas erzählen!', 'We have to tell you something!'),
('es', 'it', 'w', 'small', '', 'Es regnet.', 'It is raining.'),
('essen', 'to eat', 'v', 'food', '', 'Was gibt es zu essen?', 'What is there to eat?'),
('das Essen', 'food / meal', 'n', 'food', '', 'Das Essen ist heute sehr gut.', 'The food is very good today.'),
('euer', 'your (plural, informal)', 'w', 'small', '', 'Euer Kurs beginnt heute.', 'Your course starts today.'),
]
