# Goethe-Zertifikat A1 word list, M–R. Same format as goethe_a_e.py.
ROWS = [
('machen', 'to do / to make', 'v', 'verb', '', 'Was machst du heute Abend?', 'What are you doing tonight?'),
('Das macht nichts.', 'It doesn\'t matter.', 'p', 'small', '', 'Entschuldigung! – Das macht nichts.', 'Sorry! – It doesn\'t matter.'),
('das Mädchen', 'girl', 'n', 'fam', 'Mädchen', 'Familie Kurz bekommt ein Baby. – Junge oder Mädchen?', 'The Kurz family is having a baby. – Boy or girl?'),
('man', 'one / you (people in general)', 'w', 'small', '', 'Hier darf man nicht rauchen.', 'You are not allowed to smoke here.'),
('der Mann', 'man / husband', 'n', 'fam', 'Männer', 'Mein Mann arbeitet bei der Polizei.', 'My husband works for the police.'),
('männlich', 'male', 'a', 'per', '', 'Kreuzen Sie bitte an: „weiblich“ oder „männlich“.', 'Please tick: "female" or "male".'),
('die Maschine', 'machine', 'n', 'home', 'Maschinen', 'Die Waschmaschine ist günstig.', 'The washing machine is cheap.'),
('das Meer', 'sea', 'n', 'nat', 'Meere', 'Wir machen Urlaub am Meer.', 'We are going on holiday by the sea.'),
('mehr', 'more', 'w', 'num', '', 'Dieses Auto kostet 1.000 Euro mehr als das andere.', 'This car costs 1,000 euros more than the other one.'),
('mein', 'my', 'w', 'small', '', 'Mein Vater ist Arzt.', 'My father is a doctor.'),
('die meisten', 'most (of)', 'w', 'small', '', 'Die meisten Norddeutschen sind sehr groß.', 'Most northern Germans are very tall.'),
('der Mensch', 'person / human being', 'n', 'fam', 'Menschen', 'Die Menschen sind hier anders als bei uns.', 'People here are different from where I come from.'),
('mieten', 'to rent', 'v', 'home', '', 'Ich möchte ein Auto mieten.', 'I would like to rent a car.'),
('die Miete', 'rent', 'n', 'home', 'Mieten', 'Die Miete für diese Wohnung ist 600 Euro.', 'The rent for this apartment is 600 euros.'),
('die Milch', 'milk', 'n', 'food', '', 'Die Milch steht im Kühlschrank.', 'The milk is in the fridge.'),
('mit', 'with / by (transport)', 'w', 'small', '', 'Trinken Sie den Kaffee mit Milch?', 'Do you take your coffee with milk?'),
('mitbringen', 'to bring along', 'v', 'verb', '', 'Ich gehe einkaufen. Soll ich dir was mitbringen?', 'I\'m going shopping. Shall I bring you something?'),
('mitkommen', 'to come along', 'v', 'verb', '', 'Ich gehe ins Kino. Kommst du mit?', 'I\'m going to the cinema. Are you coming?'),
('mitmachen', 'to join in', 'v', 'verb', '', 'Warum macht ihr nicht mit?', 'Why don\'t you join in?'),
('mitnehmen', 'to take along', 'v', 'verb', '', 'Nehmen wir meine Schwester ins Kino mit?', 'Shall we take my sister to the cinema?'),
('die Mitte', 'middle / centre', 'n', 'town', '', 'Der Lehrer steht in der Mitte des Klassenzimmers.', 'The teacher stands in the middle of the classroom.'),
('die Möbel', 'furniture (plural)', 'n', 'home', '', 'Sind die Möbel neu?', 'Is the furniture new?'),
('möchten', 'would like', 'v', 'verb', '', 'Was möchten Sie trinken?', 'What would you like to drink?'),
('mögen', 'to like', 'v', 'feel', '', 'Magst du Kaffee oder Tee?', 'Do you like coffee or tea?'),
('möglich', 'possible', 'a', 'desc', '', 'Mit dieser Fahrkarte ist die Fahrt ab 9 Uhr möglich.', 'With this ticket you can travel from 9 o\'clock.'),
('der Moment', 'moment', 'n', 'time', 'Momente', 'Einen Moment bitte.', 'One moment, please.'),
('morgen', 'tomorrow', 'd', 'time', '', 'Morgen beginnt die Schule um 10 Uhr.', 'Tomorrow school starts at 10 o\'clock.'),
('müde', 'tired', 'a', 'feel', '', 'Ich bin müde. Ich gehe schlafen.', 'I\'m tired. I\'m going to bed.'),
('der Mund', 'mouth', 'n', 'body', 'Münder', 'Öffnen Sie den Mund.', 'Open your mouth.'),
('müssen', 'must / to have to', 'v', 'verb', '', 'Ich muss jeden Tag von 8 bis 18 Uhr arbeiten.', 'I have to work from 8 a.m. to 6 p.m. every day.'),
('die Mutter', 'mother', 'n', 'fam', 'Mütter', 'Frau Berghäuser ist die Mutter von Michaela.', 'Mrs Berghäuser is Michaela\'s mother.'),
('nach', 'to / after', 'w', 'small', '', 'Ich fliege nach München.', 'I am flying to Munich.'),
('nächster', 'next', 'a', 'time', '', 'Sehen wir uns nächste Woche?', 'Shall we see each other next week?'),
('der Name', 'name', 'n', 'per', 'Namen', 'Mein Name ist Thomas Schmidt.', 'My name is Thomas Schmidt.'),
('nehmen', 'to take', 'v', 'verb', '', 'Ich nehme den Bus.', 'I\'ll take the bus.'),
('nein', 'no', 'p', 'small', '', 'Fährst du auch nach München? – Nein, ich habe keine Zeit.', 'Are you going to Munich too? – No, I don\'t have time.'),
('neu', 'new', 'a', 'desc', '', 'Wir haben eine neue Wohnung.', 'We have a new apartment.'),
('nicht', 'not', 'w', 'small', '', 'Das stimmt nicht.', 'That is not right.'),
('nichts', 'nothing', 'w', 'small', '', 'Hier kaufe ich nichts. Der Laden gefällt mir nicht.', 'I\'m not buying anything here. I don\'t like the shop.'),
('noch', 'still / yet / another', 'w', 'small', '', 'Wir warten noch fünf Minuten.', 'We\'ll wait another five minutes.'),
('normal', 'normal', 'a', 'desc', '', 'Sein Gewicht ist normal.', 'His weight is normal.'),
('die Nummer', 'number', 'n', 'num', 'Nummern', 'Können Sie mir Ihre Nummer geben?', 'Can you give me your number?'),
('nur', 'only', 'w', 'small', '', 'Ich möchte nur ein Glas Wasser.', 'I only want a glass of water.'),
('oben', 'upstairs / at the top', 'd', 'small', '', 'Ich wohne oben.', 'I live upstairs.'),
('das Obst', 'fruit', 'n', 'food', '', 'Im Sommer ist das Obst billig.', 'In summer fruit is cheap.'),
('oder', 'or', 'w', 'small', '', 'Wann können Sie kommen – heute oder morgen?', 'When can you come – today or tomorrow?'),
('öffnen', 'to open', 'v', 'verb', '', 'Ich öffne die Tür.', 'I open the door.'),
('geöffnet', 'open', 'a', 'shop', '', 'Der Laden ist samstags bis 16 Uhr geöffnet.', 'The shop is open until 4 p.m. on Saturdays.'),
('oft', 'often', 'd', 'time', '', 'Petra treffe ich oft.', 'I often meet Petra.'),
('ohne', 'without', 'w', 'small', '', 'Ohne Geld kann er nichts kaufen.', 'Without money he can\'t buy anything.'),
('das Öl', 'oil', 'n', 'food', 'Öle', 'Den Salat machen wir ohne Öl.', 'We make the salad without oil.'),
('die Oma', 'grandma', 'n', 'fam', 'Omas', 'Meine Oma wohnt bei uns.', 'My grandma lives with us.'),
('der Opa', 'grandpa', 'n', 'fam', 'Opas', 'Mein Opa heißt Hans.', 'My grandpa is called Hans.'),
('die Ordnung', 'order', 'n', 'small', '', 'Das ist in Ordnung.', 'That\'s all right.'),
('der Ort', 'place / town', 'n', 'town', 'Orte', 'Der Ort liegt am Meer.', 'The town is by the sea.'),
('das Papier', 'paper', 'n', 'work', 'Papiere', 'Hier sind Papier und Bleistift.', 'Here are paper and a pencil.'),
('die Papiere', 'documents (plural)', 'n', 'per', '', 'Haben Sie Ihre Papiere dabei?', 'Do you have your documents with you?'),
('der Partner', 'partner (male)', 'n', 'fam', 'Partner', 'Das ist mein Partner.', 'This is my partner.'),
('die Partnerin', 'partner (female)', 'n', 'fam', 'Partnerinnen', 'Sie ist meine Partnerin.', 'She is my partner.'),
('die Party', 'party', 'n', 'free', 'Partys', 'Heute Abend machen wir eine Party.', 'We are having a party tonight.'),
('der Pass', 'passport', 'n', 'per', 'Pässe', 'Im Hotel brauchst du deinen Pass.', 'You need your passport at the hotel.'),
('die Pause', 'break', 'n', 'work', 'Pausen', 'Von 12 bis 12.30 Uhr haben wir Mittagspause.', 'We have a lunch break from 12 to 12.30.'),
('der Plan', 'plan / map', 'n', 'trav', 'Pläne', 'Ich kaufe mir einen Stadtplan.', 'I\'m buying a city map.'),
('der Platz', 'seat / square / space', 'n', 'town', 'Plätze', 'Tut mir leid, der Platz ist besetzt.', 'Sorry, this seat is taken.'),
('die Polizei', 'police', 'n', 'town', '', 'Holen Sie die Polizei!', 'Call the police!'),
('die Pommes frites', 'chips / French fries (plural)', 'n', 'food', '', 'Die Kinder essen Hähnchen mit Pommes frites.', 'The children are eating chicken with chips.'),
('die Post', 'post office / mail', 'n', 'comm', '', 'Wo ist die Post, bitte?', 'Where is the post office, please?'),
('die Postleitzahl', 'postcode', 'n', 'per', 'Postleitzahlen', 'Wie ist Ihre Postleitzahl?', 'What is your postcode?'),
('das Praktikum', 'internship', 'n', 'work', 'Praktika', 'Ich mache ein Praktikum bei Siemens.', 'I am doing an internship at Siemens.'),
('die Praxis', 'doctor\'s practice / surgery', 'n', 'body', 'Praxen', 'Die Praxis ist ab acht Uhr geöffnet.', 'The surgery is open from eight o\'clock.'),
('der Preis', 'price', 'n', 'shop', 'Preise', 'Die Preise sind hoch.', 'The prices are high.'),
('das Problem', 'problem', 'n', 'small', 'Probleme', 'Mein Problem ist die Sprache.', 'My problem is the language.'),
('der Prospekt', 'brochure', 'n', 'trav', 'Prospekte', 'Bitte schicken Sie mir einen Prospekt von Ihrem Hotel.', 'Please send me a brochure of your hotel.'),
('die Prüfung', 'exam', 'n', 'work', 'Prüfungen', 'Die Prüfung ist am Montag um 8 Uhr.', 'The exam is on Monday at 8 o\'clock.'),
('pünktlich', 'punctual / on time', 'a', 'time', '', 'Der Bus fährt pünktlich um acht Uhr.', 'The bus leaves punctually at eight o\'clock.'),
('Rad fahren', 'to cycle', 'v', 'free', '', 'Das Kind kann schon Rad fahren.', 'The child can already ride a bike.'),
('rauchen', 'to smoke', 'v', 'verb', '', 'Ich rauche nicht.', 'I don\'t smoke.'),
('der Raum', 'room', 'n', 'home', 'Räume', 'Der Unterricht ist in Raum 332.', 'The lesson is in room 332.'),
('die Rechnung', 'bill / invoice', 'n', 'shop', 'Rechnungen', 'Die Rechnung, bitte.', 'The bill, please.'),
('rechts', 'right (direction)', 'd', 'town', '', 'Die Schillerstraße ist hier rechts.', 'Schillerstraße is here on the right.'),
('regnen', 'to rain', 'v', 'nat', '', 'Heute regnet es.', 'It is raining today.'),
('der Regen', 'rain', 'n', 'nat', '', 'Bei diesem Regen gehe ich nicht raus.', 'I\'m not going out in this rain.'),
('der Reis', 'rice', 'n', 'food', '', 'Ich esse gern Reis.', 'I like eating rice.'),
('reisen', 'to travel', 'v', 'trav', '', 'Ich reise gern.', 'I like travelling.'),
('die Reise', 'journey / trip', 'n', 'trav', 'Reisen', 'Wir machen eine Reise nach Österreich.', 'We are taking a trip to Austria.'),
('das Reisebüro', 'travel agency', 'n', 'trav', 'Reisebüros', 'Mein Mann arbeitet im Reisebüro.', 'My husband works at the travel agency.'),
('der Reiseführer', 'guidebook / tour guide', 'n', 'trav', 'Reiseführer', 'Ich kaufe mir einen Reiseführer von Berlin.', 'I\'m buying a guidebook for Berlin.'),
('reparieren', 'to repair', 'v', 'verb', '', 'Er hat das Fahrrad repariert.', 'He repaired the bike.'),
('die Reparatur', 'repair', 'n', 'home', 'Reparaturen', 'Die Reparatur ist sehr teuer.', 'The repair is very expensive.'),
('das Restaurant', 'restaurant', 'n', 'town', 'Restaurants', 'Wir essen heute in einem Restaurant.', 'We are eating in a restaurant today.'),
('die Rezeption', 'reception (hotel)', 'n', 'trav', 'Rezeptionen', 'Fragen Sie bitte im Hotel an der Rezeption.', 'Please ask at the hotel reception.'),
('richtig', 'correct / right', 'a', 'desc', '', 'Habe ich das richtig verstanden?', 'Did I understand that correctly?'),
('riechen', 'to smell', 'v', 'verb', '', 'Dieser Wein riecht gut.', 'This wine smells good.'),
('ruhig', 'quiet / calm', 'a', 'desc', '', 'Ich möchte ein ruhiges Zimmer.', 'I would like a quiet room.'),
]
